# -*- coding: utf-8 -*-
from __future__ import unicode_literals

COSINNUS_DATETIMEPICKER_DATETIME_FORMAT = 'DD.MM.YYYY HH:mm'
COSINNUS_DATETIMEPICKER_DATE_FORMAT = 'DD.MM.YYYY'
COSINNUS_DATETIMEPICKER_TIME_FORMAT = 'HH:mm'
COSINNUS_DJANGO_DATE_FORMAT = 'j.n.Y'
COSINNUS_DJANGO_DATE_SHORT_FORMAT = 'j.n.'
COSINNUS_DJANGO_DATE_SHORT_CLEAR_FORMAT = 'j.M'
COSINNUS_DJANGO_TIME_FORMAT = 'H:i'
COSINNUS_DJANGO_DATETIME_FORMAT = 'j.n.Y H:i'
