# Generated by Django 2.1.15 on 2021-05-07 17:32

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus_organization', '0002_auto_20201008_1118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cosinnusorganizationgroup',
            options={'verbose_name': 'Organization group', 'verbose_name_plural': 'Organization groups'},
        ),
        migrations.AddField(
            model_name='cosinnusorganization',
            name='settings',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='cosinnusorganization',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Civil society organization'), (2, 'Company (commercial)'), (3, 'Public institution'), (0, 'Other')], verbose_name='Organization type'),
        ),
    ]
