# Generated by Django 3.2 on 2022-01-26 10:28

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus_organization', '0003_auto_20210507_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosinnusorganization',
            name='extra_fields',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='cosinnusorganization',
            name='settings',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        )
    ]
