# Generated by Django 2.1.15 on 2021-05-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus_organization', '0005_auto_20210516_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosinnusorganization',
            name='is_open_for_cooperation',
            field=models.BooleanField(null=True, verbose_name='Open for cooperation'),
        ),
    ]
