# Generated by Django 2.1.15 on 2021-10-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus_organization', '0005_cosinnusorganization_is_open_for_cooperation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosinnusorganization',
            name='is_open_for_cooperation',
            field=models.BooleanField(default=False, verbose_name='Open for cooperation'),
        ),
    ]
