# Generated by Django 2.1.15 on 2020-11-17 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus_event', '0012_auto_20200925_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenceevent',
            name='raw_html',
            field=models.TextField(default='', help_text='Raw HTML embed code to use instead of URL', verbose_name='Embed code (HTML)'),
        ),
    ]
