# Generated by Django 2.1.15 on 2021-01-27 16:36

import cosinnus.utils.files
import cosinnus.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus_event', '0014_auto_20201118_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_hidden_group_proxy',
            field=models.BooleanField(default=False, help_text='If set, this event is hidden in its own group, acting as a proxy for the group with from_date and to_date synced, to be able to be shown in other groups.', verbose_name='Is hidden proxy'),
        ),
        migrations.AlterField(
            model_name='conferenceevent',
            name='presentation_file',
            field=models.FileField(blank=True, help_text='The presentation file (e.g. PDF) will be pre-uploaded to the BBB room.', null=True, upload_to=cosinnus.utils.files.get_presentation_filename, validators=[cosinnus.utils.validators.validate_file_infection], verbose_name='Presentation file'),
        ),
    ]
