# Generated by Django 2.1.15 on 2021-05-19 10:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus_event', '0015_auto_20210127_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenceevent',
            name='show_chat',
            field=models.BooleanField(default=False, help_text='Show rocket chat in sidebar in event', verbose_name='Show chat'),
        ),
        migrations.AlterField(
            model_name='conferenceevent',
            name='max_participants',
            field=models.PositiveSmallIntegerField(default=500, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(512)], verbose_name='Maximum Event Participants'),
        ),
    ]
