# Generated by Django 2.1.15 on 2021-06-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus_event', '0018_event_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenceevent',
            name='enable_streaming',
            field=models.BooleanField(default=False, verbose_name='Enable Streaming'),
        ),
        migrations.AddField(
            model_name='conferenceevent',
            name='stream_key',
            field=models.CharField(blank=True, help_text='The key for this specific stream session you created at your streaming provider', max_length=250, null=True, verbose_name='Stream Key'),
        ),
        migrations.AddField(
            model_name='conferenceevent',
            name='stream_url',
            field=models.URLField(blank=True, help_text='The URL of your streaming provider to receive the incoming stream', null=True, verbose_name='Stream URL'),
        ),
    ]
