# Generated by Django 2.1.15 on 2021-07-07 13:04

import cosinnus_event.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus_event', '0019_auto_20210611_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenceevent',
            name='is_confidential',
            field=models.BooleanField(default=False, help_text="Provides an option to choose if the event's description should be shown publicly or not", verbose_name='Event is confidential'),
        ),
    ]
