# Generated by Django 2.1.15 on 2021-10-22 08:29

import cosinnus_event.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus_event', '0020_auto_20210707_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='video_conference_type',
            field=models.PositiveIntegerField(choices=[(1, 'BBB-Meeting'), (2, 'Fairmeeting'), (0, 'No video conference')], default=0, verbose_name='Type of video conference available for the event'),
        ),
    ]
