# Generated by Django 2.2 on 2022-02-18 14:11
from django.db import migrations


def set_is_confidential_to_is_description_visible_on_microsite(apps, schema_editor):
    ConferenceEvent = apps.get_model('cosinnus_event', 'ConferenceEvent')
    ConferenceEvent.objects.filter(is_confidential=True).update(is_description_visible_on_microsite=False)
        
        
def set_is_description_visible_on_microsite_to_is_confidential(apps, schema_editor):
    ConferenceEvent = apps.get_model('cosinnus_event', 'ConferenceEvent')
    ConferenceEvent.objects.filter(is_description_visible_on_microsite=False).update(is_confidential=True)
        
        
class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus_event', '0022_auto_20220218_1506'),
    ]

    operations = [
        migrations.RunPython(
            set_is_confidential_to_is_description_visible_on_microsite,
            reverse_code=set_is_description_visible_on_microsite_to_is_confidential,
        ),
    ]
