# Generated by Django 3.2.18 on 2023-08-02 11:26

import cosinnus_event.fields
from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosinnus_event', '0024_auto_20220218_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceEventAttendanceTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Start-Time')),
                ('end', models.DateTimeField(verbose_name='End-Time')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_tracking', to='cosinnus_event.conferenceevent', verbose_name='Conference Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Conference Event Attendance Tracking',
                'verbose_name_plural': 'Conference Event Attendance Trackings',
                'ordering': ['-start'],
            },
        ),
    ]
