# Generated by Django 4.2.27 on 2026-04-28 11:25

import cosinnus_event.fields
from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.COSINNUS_GROUP_OBJECT_MODEL),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosinnus_event', '0025_auto_20230802_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.PositiveIntegerField(choices=[(1, 'Scheduled'), (2, 'Voting open'), (3, 'Canceled'), (4, 'Archived Event Poll'), (5, 'Synchronized Event')], default=2, verbose_name='State'),
        ),
    ]
