# Generated by Django 4.2.27 on 2026-05-18 06:34

import cosinnus_event.fields
from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.COSINNUS_GROUP_OBJECT_MODEL),
        ('cosinnus_event', '0026_alter_event_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='nextcloud_calendar_last_sync',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Event Nextcloud Calendar CalDAV Last Sync Timestamp'),
        ),
        migrations.AddField(
            model_name='event',
            name='nextcloud_calendar_uid',
            field=models.UUIDField(blank=True, help_text='Used for synced events', null=True, unique=True, verbose_name='Event Nextcloud CalDAV UID'),
        ),
    ]
