# Generated by Django 4.2.27 on 2026-06-03 09:31

import cosinnus_event.fields
from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.COSINNUS_GROUP_OBJECT_MODEL),
        ('cosinnus_event', '0027_event_nextcloud_calendar_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='nextcloud_calendar_uid',
            field=models.CharField(blank=True, db_index=True, help_text='Used for synced events', max_length=255, null=True, unique=True, verbose_name='Event Nextcloud CalDAV UID'),
        ),
    ]
