# Generated by Django 4.2.27 on 2026-06-04 09:20

import cosinnus_event.fields
from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.COSINNUS_GROUP_OBJECT_MODEL),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosinnus_event', '0028_alter_event_nextcloud_calendar_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='nextcloud_calendar_uid',
            field=models.CharField(blank=True, db_index=True, help_text='Used for synced events', max_length=255, null=True, verbose_name='Event Nextcloud CalDAV UID'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(models.F('group'), models.F('nextcloud_calendar_uid'), name='unique_nextcloud_calendar_event_uid'),
        ),
    ]
