# Generated by Django 2.0.9 on 2018-11-16 18:44

from django.db import migrations, models


def set_last_modified(apps, schema_editor):
    CosinnusGroup = apps.get_model('cosinnus', 'CosinnusGroup')
    CosinnusGroup.objects.update(last_modified=models.F('created'))


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0041_auto_20181105_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosinnusgroup',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified'),
        ),
        migrations.RunPython(set_last_modified, migrations.RunPython.noop)
    ]
