# Generated by Django 2.1.5 on 2019-01-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0042_cosinnusgroup_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='may_be_contacted',
            field=models.BooleanField(default=False, verbose_name='May be contacted'),
        ),
    ]
