# Generated by Django 2.1.5 on 2019-02-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0043_userprofile_may_be_contacted'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosinnusportal',
            name='support_email',
            field=models.EmailField(blank=True, help_text='This email is shown to users as contact address on many pages', max_length=254, verbose_name='Support Email'),
        ),
    ]
