# Generated by Django 2.1.5 on 2019-04-08 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0044_cosinnusportal_support_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosinnusportal',
            name='tos_date',
            field=models.DateTimeField(default=datetime.datetime(1999, 1, 1, 13, 37), help_text='This is used to determine the date the newest ToS have been released, that users have acceppted. When a portal`s ToS update, set this to a newer date to have a popup come up for all users whose `settings.tos_accepted_date` is not after this date.', verbose_name='ToS Version'),
        ),
    ]
