# Generated by Django 2.1.5 on 2019-05-29 13:05

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('cosinnus', '0047_set_last_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastVisitedObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('visited', models.DateTimeField(auto_now_add=True, verbose_name='Visited')),
                ('item_data', django.contrib.postgres.fields.jsonb.JSONField(help_text='Stores a JSON representation of the target object, as converted by a `DashboardItem`.', verbose_name='Data')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lastvisited', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'LastVisited',
                'verbose_name_plural': 'LastVisiteds',
                'ordering': ('visited',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='lastvisitedobject',
            unique_together={('content_type', 'object_id', 'user')},
        ),
    ]
