# Generated by Django 2.1.10 on 2019-08-13 13:59

import cosinnus.models.mixins.indexes
import cosinnus.utils.files
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosinnus', '0050_auto_20190707_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('de', 'Deutsch--LEAVE-THIS-EMPTY-DO-NOT-TRANSLATE'), ('en', 'English--LEAVE-THIS-EMPTY-DO-NOT-TRANSLATE'), ('ru', 'Russian--LEAVE-THIS-EMPTY-DO-NOT-TRANSLATE'), ('uk', 'Ukrainian--LEAVE-THIS-EMPTY-DO-NOT-TRANSLATE'), ('fr', 'French--LEAVE-THIS-EMPTY-DO-NOT-TRANSLATE'), ('pl', 'Polish--LEAVE-THIS-EMPTY-DO-NOT-TRANSLATE'), ('be', 'Belarussian--LEAVE-THIS-EMPTY-DO-NOT-TRANSLATE')], default='de', max_length=2, verbose_name='Language'),
        ),
    ]
