# Generated by Django 2.1.10 on 2020-02-02 12:10

from django.db import migrations
from cosinnus.conf import settings


def follow_all_your_groups(apps, schema_editor):
    """ One-Time makes all users follow all groups they are a member of admin of. """
    
    CosinnusGroupMembership = apps.get_model("cosinnus", "CosinnusGroupMembership")
    ContentType = apps.get_model("contenttypes", "ContentType")
    LikeObject = apps.get_model("cosinnus", "LikeObject")
    
    app_label, model_name = settings.COSINNUS_GROUP_OBJECT_MODEL.split('.')
    group_ct = ContentType.objects.get_for_model(apps.get_model(app_label, model_name))
    
    # for each group membership (member or admin status only)
    for membership in CosinnusGroupMembership.objects.filter(status__in=[1, 2]):
        # either create a following likeobject
        likeobj, created = LikeObject.objects.get_or_create(
            content_type=group_ct, 
            object_id=membership.group_id, 
            user_id=membership.user_id,
            defaults={'liked': False, 'followed': True}
        )
        # or make the existing likeobject followed
        if not created:
            if not likeobj.followed:
                likeobj.followed = True
                likeobj.save(update_fields=['followed'])
        
    
class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0051_auto_20191017_2138'),
    ]

    operations = [
        migrations.RunPython(follow_all_your_groups, migrations.RunPython.noop),
    ]
