# Generated by Django 2.1.15 on 2020-02-23 15:11

import cosinnus.models.mixins.images
import cosinnus.utils.files
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosinnus', '0052_auto_20200122_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDashboardAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, help_text='If an idea is not active, it counts as non-existent for all purposes and views on the website.', verbose_name='Is active')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Text Editor'), (1, 'Raw HTML')], default=0, help_text='Whether the announcement displays markdown text from an editor field or raw pasted HTML.', verbose_name='Announcement Display Type')),
                ('valid_from', models.DateTimeField(help_text='The announcement will not be shown before this date.', verbose_name='Valid From')),
                ('valid_till', models.DateTimeField(help_text='The announcement will not be shown after this date.', verbose_name='Valid From')),
                ('title', models.CharField(help_text='Internal title field only.', max_length=250, verbose_name='Title')),
                ('slug', models.SlugField(help_text='Be extremely careful when changing this slug manually! There can be many side-effects (redirects breaking e.g.)!', verbose_name='Slug')),
                ('category', models.PositiveSmallIntegerField(choices=[(0, '(none displayed)'), (1, 'Announcement'), (2, 'Maintenance'), (3, 'Update'), (4, 'Technical Issues'), (5, 'Miscellaneous')], default=0, help_text='A selection of text headlines to display as header', verbose_name='Announcement Category')),
                ('text', models.TextField(blank=True, help_text='Main text of this announcement.', verbose_name='Text')),
                ('raw_html', models.TextField(blank=True, help_text='Raw HTML for this announcement.', verbose_name='Raw HTML')),
                ('image', models.ImageField(blank=True, help_text='Shown as large banner image', max_length=250, null=True, upload_to=cosinnus.utils.files.get_user_dashboard_announcement_image_filename, verbose_name='Image')),
                ('url', models.URLField(blank=True, help_text='For the "read more" button', null=True, verbose_name='URL')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('portal', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cosinnus.CosinnusPortal', verbose_name='Portal')),
            ],
            options={
                'ordering': ('-valid_from',),
            },
            bases=(cosinnus.models.mixins.images.ThumbnailableImageMixin, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='userdashboardannouncement',
            unique_together={('slug', 'portal')},
        ),
    ]
