# Generated by Django 2.1.15 on 2020-03-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0053_auto_20200223_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosinnusportal',
            name='video_conference_server',
            field=models.URLField(blank=True, help_text='If entered, will enable video conference functionality across the site. Needs to be a URL up to the point where any random room name can be appended.', max_length=250, null=True, verbose_name='Video Conference Server'),
        ),
    ]
