# Generated by Django 2.1.15 on 2020-04-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0054_auto_20200321_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosinnusgroup',
            name='embedded_dashboard_html',
            field=models.TextField(blank=True, help_text='A field with custom HTML that will be shown to all group members on the group dashboard', null=True, verbose_name='Embedded Dashboard HTML'),
        ),
    ]
