# Generated by Django 2.1.15 on 2020-06-24 13:35

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0056_auto_20200515_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosinnusgroup',
            name='is_conference',
            field=models.BooleanField(default=False, help_text='If a group is marked as workshop it is possible to auto-generate accounts for workshop participants', verbose_name='Is workshop'),
        ),
        migrations.AddField(
            model_name='cosinnusgroup',
            name='conference_is_running',
            field=models.BooleanField(default=False, help_text='Determins whether a group that is marked as workshop is running', verbose_name='Workshop is running'),
        )
    ]
