# Generated by Django 2.1.15 on 2020-06-10 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0051_auto_20190813_1559'),
        ('cosinnus', '0056_auto_20200515_1448'),
    ]

    operations = [
    ]