# Generated by Django 2.1.15 on 2020-09-01 12:59

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosinnus', '0057_add_workshop_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='BBBRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_token', django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='member token mapping')),
                ('token', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=160, null=True, verbose_name='room name or title')),
                ('members', models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL)),
                ('moderators', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('presenter', models.ForeignKey(blank=True, help_text='this user will enter the BBB presenter mode for this conversation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presenter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='cosinnusgroup',
            name='conference_is_running',
            field=models.BooleanField(default=False, help_text='Determins whether a group that is marked as conference is running', verbose_name='Conference is running'),
        ),
        migrations.AlterField(
            model_name='cosinnusgroup',
            name='is_conference',
            field=models.BooleanField(default=False, help_text='If a group is marked as conference it is possible to auto-generate accounts for workshop participants', verbose_name='Is conference'),
        ),
        migrations.AlterField(
            model_name='tagobject',
            name='topics',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Topics'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('de', 'Deutsch--NATIVE-LANGUAGE'), ('en', 'English--NATIVE-LANGUAGE'), ('ru', 'Russian--NATIVE-LANGUAGE'), ('uk', 'Ukrainian--NATIVE-LANGUAGE'), ('fr', 'French--NATIVE-LANGUAGE'), ('pl', 'Polish--NATIVE-LANGUAGE'), ('be', 'Belarussian--NATIVE-LANGUAGE'), ('nl', 'Dutch--NATIVE-LANGUAGE')], default='de', max_length=2, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='tagobject',
            name='bbb_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cosinnus.BBBRoom', verbose_name='BigBlueButton conversation room'),
        ),
    ]
