# Generated by Django 2.1.15 on 2020-09-12 19:59

import cosinnus.models.bbb_room
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosinnus', '0057_add_workshop_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='BBBRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_id', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=160, null=True, verbose_name='room name or title')),
                ('moderator_password', models.CharField(default=cosinnus.models.bbb_room.random_password, help_text='the password set to enter the room as a moderator', max_length=30)),
                ('attendee_password', models.CharField(blank=True, default='', help_text='the password set to enter the room as a attendee', max_length=30, null=True)),
                ('welcome_message', models.CharField(blank=True, help_text='the welcome message, that is displayed to attendees', max_length=300, null=True, verbose_name='the rooms welcome message')),
                ('max_participants', models.PositiveIntegerField(default=None, help_text='maximum number in the conference at the same time', null=True, verbose_name='maximum number of users')),
                ('dial_number', models.CharField(blank=True, default='', help_text='number for dialing into the conference via telephone', max_length=20, null=True, verbose_name='telephone dial in number')),
                ('voice_bridge', models.PositiveIntegerField(default=cosinnus.models.bbb_room.random_voice_bridge, help_text='pin to enter for telephone participants', unique=True, validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(99999)], verbose_name='dial in PIN')),
                ('internal_meeting_id', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_meeting_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ended', models.BooleanField(default=False)),
                ('attendees', models.ManyToManyField(related_name='attendees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(help_text='verbose description of the conference')),
            ],
        ),
        migrations.AlterField(
            model_name='cosinnusgroup',
            name='conference_is_running',
            field=models.BooleanField(default=False, help_text='Determins whether a group that is marked as conference is running', verbose_name='Conference is running'),
        ),
        migrations.AlterField(
            model_name='cosinnusgroup',
            name='is_conference',
            field=models.BooleanField(default=False, help_text='If a group is marked as conference it is possible to auto-generate accounts for workshop participants', verbose_name='Is conference'),
        ),
        migrations.AlterField(
            model_name='tagobject',
            name='topics',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Topics'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('de', 'Deutsch--NATIVE-LANGUAGE'), ('en', 'English--NATIVE-LANGUAGE'), ('ru', 'Russian--NATIVE-LANGUAGE'), ('uk', 'Ukrainian--NATIVE-LANGUAGE'), ('fr', 'French--NATIVE-LANGUAGE'), ('pl', 'Polish--NATIVE-LANGUAGE'), ('be', 'Belarussian--NATIVE-LANGUAGE'), ('nl', 'Dutch--NATIVE-LANGUAGE')], default='de', max_length=2, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='conference',
            name='group',
            field=models.ForeignKey(help_text='group associated with the conference', on_delete=django.db.models.deletion.CASCADE, to=settings.COSINNUS_GROUP_OBJECT_MODEL, verbose_name='conference group'),
        ),
        migrations.AddField(
            model_name='bbbroom',
            name='conference',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cosinnus.Conference'),
        ),
        migrations.AddField(
            model_name='bbbroom',
            name='moderators',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bbbroom',
            name='presenter',
            field=models.ForeignKey(blank=True, help_text='this user will enter the BBB presenter mode for this conversation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presenter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tagobject',
            name='bbb_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cosinnus.BBBRoom', verbose_name='BigBlueButton conversation room'),
        ),
    ]
