# Generated by Django 2.1.15 on 2020-09-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0058_auto_20200912_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='end',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
