# Generated by Django 2.1.15 on 2020-09-02 13:32

import cosinnus.models.bbb_room
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0058_auto_20200901_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbbroom',
            name='attendee_password',
            field=models.CharField(blank=True, default='', help_text='the password set to enter the room as a attendee', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bbbroom',
            name='moderator_password',
            field=models.CharField(default=cosinnus.models.bbb_room.random_password, help_text='the password set to enter the room as a moderator', max_length=30),
        ),
        migrations.AddField(
            model_name='bbbroom',
            name='welcome_message',
            field=models.CharField(blank=True, help_text='the welcome message, that is displayed to attendees', max_length=300, null=True, verbose_name='the rooms welcome message'),
        ),
        migrations.AlterField(
            model_name='bbbroom',
            name='member_token',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='member token mapping'),
        ),
    ]
