# Generated by Django 2.1.15 on 2020-09-14 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0059_auto_20200913_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='group',
        ),
        migrations.RemoveField(
            model_name='bbbroom',
            name='conference',
        ),
        migrations.DeleteModel(
            name='Conference',
        ),
    ]
