# Generated by Django 2.1.15 on 2020-09-15 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0059_add_conference_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbbroom',
            name='portal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bbb_rooms', to='cosinnus.CosinnusPortal', verbose_name='Portal'),
        ),
    ]
