# Generated by Django 2.1.15 on 2020-09-09 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0059_auto_20200902_1532'),
        ('cosinnus', '0058_add_sdgs_json_field'),
    ]

    operations = [
    ]
