# Generated by Django 2.1.15 on 2020-10-05 10:43

import cosinnus.models.mixins.indexes
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import re


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0059_auto_20201005_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosinnusgroup',
            name='extra_fields',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='cosinnusorganization',
            name='extra_fields',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
    ]
