# Generated by Django 2.1.15 on 2020-09-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0059_auto_20200902_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbbroom',
            name='dial_number',
            field=models.CharField(blank=True, default='', help_text='number for dialing into the conference via telephone', max_length=20, null=True, verbose_name='telephone dial in number'),
        ),
        migrations.AddField(
            model_name='bbbroom',
            name='ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bbbroom',
            name='max_attendees',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='bbbroom',
            name='parent_meeting_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
