# Generated by Django 2.1.15 on 2020-09-14 09:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0060_auto_20200914_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbbroom',
            name='options',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='options for the room, that are represented in the bigbluebutton API', null=True, verbose_name='room options'),
        ),
    ]
