# Generated by Django 2.1.15 on 2020-09-08 10:35

import cosinnus.models.bbb_room
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0060_auto_20200907_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bbbroom',
            name='max_attendees',
        ),
        migrations.AddField(
            model_name='bbbroom',
            name='internal_meeting_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bbbroom',
            name='max_participants',
            field=models.PositiveIntegerField(default=None, help_text='maximum number in the conference at the same time', null=True, verbose_name='maximum number of users'),
        ),
        migrations.AddField(
            model_name='bbbroom',
            name='voice_bridge',
            field=models.PositiveIntegerField(default=cosinnus.models.bbb_room.random_voice_bridge, help_text='pin to enter for telephone participants', unique=True, validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(99999)], verbose_name='dial in PIN'),
        ),
    ]
