# Generated by Django 2.1.15 on 2020-09-11 13:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosinnus', '0060_merge_20200909_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='CosinnusConferenceRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('slug', models.SlugField(help_text='Be extremely careful when changing this slug manually! There can be many side-effects (redirects breaking e.g.)!', verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Short Description')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Lobby'), (1, 'Stage'), (2, 'Workshops'), (3, 'Discussions'), (4, 'Coffee Tables'), (5, 'Results')], default=0, verbose_name='Conference Room Type')),
                ('is_visible', models.BooleanField(default=True, help_text='If a room is not visible, it is not shown in any room lists', verbose_name='Is visible')),
                ('sort_index', models.PositiveSmallIntegerField(default=1, help_text='Rooms are ordered in ascending order on this field', verbose_name='Sorting index')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('rocket_chat_room_id', models.CharField(max_length=250, null=True, verbose_name='RocketChat room id')),
                ('allow_user_table_creation', models.BooleanField(default=False, help_text='Otherwise, only organisers can create new tables', verbose_name='Allow users to create new coffee tables')),
                ('max_coffeetable_participants', models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(512)], verbose_name='Maximum Coffee Table Participants')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cosinnus_cosinnusconferenceroom_set', to=settings.COSINNUS_GROUP_OBJECT_MODEL, verbose_name='Team')),
                ('target_result_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.COSINNUS_GROUP_OBJECT_MODEL, verbose_name='Result Project')),
            ],
            options={
                'verbose_name': 'Conference Room',
                'verbose_name_plural': 'CConference Rooms',
                'ordering': ('sort_index', 'title'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='cosinnusconferenceroom',
            unique_together={('slug', 'group')},
        ),
    ]
