# Generated by Django 2.1.15 on 2020-09-17 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0061_auto_20200916_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosinnusconferenceroom',
            name='target_result_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conference_room', to=settings.COSINNUS_GROUP_OBJECT_MODEL, verbose_name='Result Project'),
        ),
    ]
