# Generated by Django 2.1.15 on 2020-09-15 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0061_bbbroom_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagobject',
            name='bbb_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tagged_objects', to='cosinnus.BBBRoom', verbose_name='BigBlueButton conversation room'),
        ),
    ]
