# Generated by Django 2.1.15 on 2020-09-20 19:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0062_auto_20200917_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosinnusgroup',
            name='conference_theme_color',
            field=models.CharField(blank=True, help_text='Conference theme color for conference groups only (css hex value, with or without "#")', max_length=10, null=True, validators=[django.core.validators.MaxLengthValidator(7)], verbose_name='Conference theme color'),
        ),
        migrations.AlterField(
            model_name='cosinnusconferenceroom',
            name='rocket_chat_room_id',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='RocketChat room id'),
        ),
    ]
