# Generated by Django 2.1.15 on 2020-09-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0063_auto_20200920_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosinnusconferenceroom',
            name='rocket_chat_room_name',
            field=models.CharField(blank=True, help_text='The verbose room name for linking URLs', max_length=250, null=True, verbose_name='RocketChat room name'),
        ),
    ]
