# Generated by Django 2.1.15 on 2020-09-24 09:04

import cosinnus.utils.bigbluebutton
import django.core.validators
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0065_auto_20200922_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='extra_fields',
            field=jsonfield.fields.JSONField(default={}, help_text='Extra userprofile fields for each portal, as defined in `settings.COSINNUS_USERPROFILE_EXTRA_FIELDS`'),
        ),
        migrations.AlterField(
            model_name='bbbroom',
            name='meeting_id',
            field=models.CharField(default=cosinnus.utils.bigbluebutton.random_meeting_id, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='bbbroom',
            name='moderator_password',
            field=models.CharField(default=cosinnus.utils.bigbluebutton.random_password, help_text='the password set to enter the room as a moderator', max_length=30),
        ),
        migrations.AlterField(
            model_name='bbbroom',
            name='voice_bridge',
            field=models.PositiveIntegerField(default=cosinnus.utils.bigbluebutton.random_voice_bridge, help_text='pin to enter for telephone participants', validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(99999)], verbose_name='dial in PIN'),
        ),
        migrations.AlterField(
            model_name='cosinnusconferenceroom',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Lobby'), (1, 'Stage'), (2, 'Workshops'), (3, 'Discussions'), (4, 'Coffee Tables'), (5, 'Results'), (6, 'Participants')], default=0, verbose_name='Conference Room Type'),
        ),
    ]
