# Generated by Django 2.1.15 on 2020-09-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0067_auto_20200924_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbbroom',
            name='room_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'General'), (1, 'Active'), (2, 'Restricted'), (3, 'Premium')], default=0, verbose_name='Room Type'),
        ),
    ]
