# Generated by Django 2.1.15 on 2020-10-06 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0068_bbbroom_room_type'),
        ('cosinnus', '0059_auto_20201005_1015'),
    ]

    operations = [
    ]
