# Generated by Django 2.1.15 on 2020-10-18 11:24

import cosinnus.models.mixins.indexes
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import re


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0071_auto_20201014_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('recipients_source', models.CharField(blank=True, max_length=100)),
                ('sent', models.DateTimeField(blank=True, null=True)),
            ],
        )
    ]
