# Generated by Django 2.1.15 on 2020-11-26 10:52

import cosinnus.models.mixins.indexes
from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosinnus', '0072_auto_20201117_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='BBBRoomVisitStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('bbb_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='cosinnus.BBBRoom', verbose_name='BBB ROOM')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.COSINNUS_GROUP_OBJECT_MODEL, verbose_name='Group')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bbb_room_visits', to=settings.AUTH_USER_MODEL, verbose_name='Visitor')),
            ],
        ),
    ]
