# Generated by Django 2.1.15 on 2020-11-05 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0072_add_starred_flag'),
        ('cosinnus', '0072_auto_20201018_1324'),
    ]

    operations = [
    ]
