# Generated by Django 2.1.15 on 2020-11-16 07:44

from django.db import migrations
from django.db.models import F
from cosinnus.models.profile import get_user_profile_model


def set_last_action_to_created(apps, schema_editor):
    """ One-Time sets all CosinnusIdeas' `last_updated` field value 
        to its `created` field value.  """
    
    UserProfile = get_user_profile_model()
    for userprofile in UserProfile.objects.all():
        userprofile.dynamic_fields = userprofile.extra_fields
        userprofile.save()

    
class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0075_auto_20201116_0844'),
    ]

    operations = [
        migrations.RunPython(set_last_action_to_created, migrations.RunPython.noop),
    ]
