# Generated by Django 2.1.15 on 2020-11-16 07:44

from django.db import migrations
from django.db.models import F

from cosinnus.conf import settings
from cosinnus.utils.migrations import attach_swappable_dependencies
from django.core.exceptions import ImproperlyConfigured


def set_last_action_to_created(apps, schema_editor):
    """ One-Time sets all CosinnusIdeas' `last_updated` field value 
        to its `created` field value.  """
    
    try:
        app_label, model_name = settings.COSINNUS_USER_PROFILE_MODEL.split('.')
    except ValueError:
        raise ImproperlyConfigured("COSINNUS_USER_PROFILE_MODEL must be defined for this migration'")
    
    UserProfile = apps.get_model(app_label, model_name)
    for userprofile in UserProfile.objects.all():
        if userprofile.extra_fields:
            userprofile.dynamic_fields = userprofile.extra_fields
            # Update profile without triggering signals to prevent triggers during migrations
            UserProfile.objects.filter(pk=userprofile.pk).update(dynamic_fields=userprofile.extra_fields)

    
class Migration(migrations.Migration):

    dependencies = attach_swappable_dependencies([
        ('cosinnus', '0075_auto_20201116_0844'),
    ])

    operations = [
        migrations.RunPython(set_last_action_to_created, migrations.RunPython.noop),
    ]
