# Generated by Django 2.1.15 on 2020-11-16 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0075_auto_20201115_1953'),
        ('cosinnus', '0076_migrate_profile_extra_fields'),
    ]

    operations = [
    ]
