# Generated by Django 2.1.15 on 2020-12-10 08:07

import cosinnus.models.mixins.indexes
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0078_auto_20201130_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosinnusmanagedtag',
            name='slug',
            field=models.SlugField(help_text='Be extremely careful when changing this slug manually! There can be many side-effects (redirects breaking e.g.)!', max_length=250, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='cosinnususerimport',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Dry run in progress'), (1, 'Dry run finished, errors in CSV that prevent import'), (2, 'Dry run finished, waiting to start import'), (3, 'Import running'), (4, 'Import finished'), (5, 'Import failed'), (6, 'Import archived')], default=0, editable=False, verbose_name='Import state'),
        ),
    ]
