# Generated by Django 2.1.15 on 2020-12-15 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0079_auto_20201210_0907'),
        ('cosinnus', '0073_auto_20201126_1152'),
    ]

    operations = [
    ]
