# Generated by Django 2.1.15 on 2020-12-16 11:45

from django.db import migrations
from cosinnus.conf import settings

def convert_conference_types(apps, schema_editor):
    """ One-Time converts all CosinnusSocieties with is_conference=True (type=2) 
        to CosinnusConference(type=3) and meaningless is_conference flag.  """
    
    group_app_name, group_model_name = settings.COSINNUS_GROUP_OBJECT_MODEL.split('.')
    CosinnusGroup = apps.get_model(group_app_name, group_model_name)
    CosinnusPermanentRedirect = apps.get_model('cosinnus', 'CosinnusPermanentRedirect')
    for group in CosinnusGroup.objects.all():
        if group.type == 1 and group.is_conference:
            group.type = 2
            group.save()
            CosinnusPermanentRedirect.objects.get_or_create(from_portal=group.portal, from_type='group', from_slug=group.slug, to_group=group)


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0080_merge_20201215_1425'),
    ]

    operations = [
        migrations.RunPython(convert_conference_types, migrations.RunPython.noop),
    ]
