# Generated by Django 2.1.15 on 2021-01-06 13:57

import cosinnus.models.mixins.indexes
from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0081_convert_conference_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipationManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants_limit', models.IntegerField(blank=True, null=True)),
                ('application_start', models.DateTimeField(blank=True, null=True)),
                ('application_end', models.DateTimeField(blank=True, null=True)),
                ('application_conditions', models.TextField(blank=True)),
                ('application_options', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='participationmanagement',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation_management', to=settings.COSINNUS_GROUP_OBJECT_MODEL, verbose_name='Participation Management'),
        )
    ]
