# Generated by Django 2.1.15 on 2021-01-21 16:46

import cosinnus.models.mixins.indexes
from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0083_auto_20210107_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosinnusgroup',
            name='use_conference_applications',
            field=models.BooleanField(default=False, verbose_name='Determins if application management is visible in conference administration.'),
        )
    ]
