# Generated by Django 2.1.15 on 2021-01-22 16:31

import cosinnus.models.mixins.indexes
from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0084_auto_20210121_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosinnusconferenceapplication',
            name='information',
            field=models.TextField(blank=True),
        )
    ]
