# Generated by Django 2.1.15 on 2021-01-24 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0074_auto_20210124_1359'),
        ('cosinnus', '0085_auto_20210122_1731'),
    ]

    operations = [
    ]
