# Generated by Django 2.1.15 on 2021-01-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0086_merge_20210124_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosinnusgroup',
            name='from_date',
            field=models.DateTimeField(blank=True, default=None, help_text='Used for conferences to determine overall running time period.', null=True, verbose_name='Start Datetime'),
        ),
        migrations.AddField(
            model_name='cosinnusgroup',
            name='to_date',
            field=models.DateTimeField(blank=True, default=None, help_text='Used for conferences to determine overall running time period.', null=True, verbose_name='End Datetime'),
        ),
        migrations.AlterField(
            model_name='cosinnusgroup',
            name='is_conference',
            field=models.BooleanField(default=False, help_text='Note: DEPRECATED, use group.type=2 now. Delete once all portals have been migrated and checked. If a group is marked as conference it is possible to auto-generate accounts for workshop participants', verbose_name='Is conference'),
        ),
        migrations.AlterField(
            model_name='cosinnusgroup',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Project'), (1, 'Group'), (2, 'Conference')], default=0, editable=False, verbose_name='Project Type'),
        ),
    ]
