# Generated by Django 2.1.15 on 2021-01-30 19:59

import cosinnus.models.mixins.indexes
import cosinnus.utils.bigbluebutton
from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0087_auto_20210126_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosinnusconferenceapplication',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified'),
        ),
        migrations.AddField(
            model_name='cosinnusconferenceapplication',
            name='reason_for_rejection',
            field=models.TextField(blank=True),
        )
    ]
