# Generated by Django 2.1.15 on 2021-02-04 14:46

import cosinnus.models.mixins.indexes
import cosinnus.utils.bigbluebutton
from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0089_auto_20210204_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosinnusgroup',
            name='attached_objects',
            field=models.ManyToManyField(blank=True, to='cosinnus.AttachedObject'),
        ),
    ]
