# Generated by Django 2.1.15 on 2021-02-10 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0091_auto_20210209_1037'),
        ('cosinnus', '0091_migrate_conference_from_to_dates'),
    ]

    operations = [
    ]
