# Generated by Django 2.1.15 on 2020-12-16 11:45

from django.db import migrations

def create_default_portal_conference_settings(apps, schema_editor):
    from django.apps import apps as django_apps
    from cosinnus.management.initialization import ensure_default_portal_conference_settings_exist

    app_config = django_apps.get_app_config('cosinnus')
    ensure_default_portal_conference_settings_exist(
        app_config=app_config,
        verbosity=1,
        interactive=False,
        using=schema_editor.connection.alias,
        apps=apps
    )


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0095_auto_20210217_1022'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RunPython(create_default_portal_conference_settings, migrations.RunPython.noop)
    ]
