# Generated by Django 2.1.15 on 2021-03-01 11:07

import cosinnus.models.mixins.indexes
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0098_auto_20210227_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosinnusconferencesettings',
            name='bbb_server_choice_premium',
            field=models.PositiveSmallIntegerField(choices=[(0, 'bbb14.wechange.de')], default=0, help_text='The chosen BBB-Server/Cluster setting for the generic object, that will be used when the group of that object is currently in its premium state. WARNING: changing this will cause new meeting connections to use the new server, even for ongoing meetings on the old server, essentially splitting a running meeting in two!', verbose_name='BBB Server for Premium Conferences'),
        ),
        migrations.AddField(
            model_name='cosinnusgroup',
            name='is_premium_currently',
            field=models.BooleanField(default=False, editable=False, help_text='Flag whether this is currently in premium mode because of a booking, changed automatically by the system.', verbose_name='Conference is currrently premium'),
        ),
        migrations.AddField(
            model_name='cosinnusgroup',
            name='is_premium_permanently',
            field=models.BooleanField(default=False, help_text='If enabled, this will always be in premium mode, independent of any bookings. WARNING: changing this may (depending on the event/conference/portal settings) cause new meeting connections to use the new server, even for ongoing meetings on the old server, essentially splitting a running meeting in two!', verbose_name='Conference is permanently premium'),
        ),
    ]
