# Generated by Django 2.1.15 on 2021-03-07 14:27

import cosinnus.models.mixins.indexes
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re

_MEMBERSHIP_MODE_APPLICATION = 1

class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0099_auto_20210301_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosinnusgroup',
            name='membership_mode',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Application method', choices=[(0, 'Regular membership requests'), (1, 'Require participation applications for this conference'), (2, 'Everyone may join')]),
        ),
    ]
