# Generated by Django 2.1.15 on 2021-03-07 14:27

import cosinnus.models.mixins.indexes
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re

class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0101_convert_use_conference_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cosinnusgroup',
            name='use_conference_applications',
        ),
    ]
