# Generated by Django 2.1.15 on 2021-04-01 15:57

import cosinnus.utils.bigbluebutton
from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0102_remove_use_conference_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalusernotificationsetting',
            name='rocketchat_setting',
            field=models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'All direct messages and mentions')], default=0, help_text='Determines if the user wants rocketchat notification emails'),
        ),
    ]
