# Generated by Django 2.1.15 on 2021-05-02 11:27

import cosinnus.utils.bigbluebutton
from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0103_auto_20210401_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='deletion_triggered_by_self',
            field=models.BooleanField(default=False, verbose_name='Deletion triggered by self'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='scheduled_for_deletion_at',
            field=models.DateTimeField(blank=True, default=None, help_text='The date this profile is scheduled for deletion. Will be deleted after this date (ONLY IF the user account is set to inactive!)', null=True, verbose_name='Scheduled for Deletion at'),
        ),
    ]
