# Generated by Django 2.1.15 on 2021-05-19 19:03

import cosinnus.utils.bigbluebutton
from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0106_mark_inactive_users_for_deletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosinnusgroup',
            name='is_open_for_cooperation',
            field=models.BooleanField(null=True, verbose_name='Open for cooperation'),
        ),
    ]
