# Generated by Django 2.1.15 on 2021-05-18 15:54

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0107_auto_20210515_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cosinnusconferencepremiumcapacityinfo',
            options={'ordering': ('from_date',), 'verbose_name': 'Conference Total Premium Capacity Info', 'verbose_name_plural': 'Conference Total Premium Capacity Infos'},
        ),
        migrations.AlterField(
            model_name='cosinnusconferencepremiumblock',
            name='from_date',
            field=models.DateField(blank=True, default=None, help_text='During this time, the conference will be using the premium BBB server.', null=True, verbose_name='Start Datetime'),
        ),
        migrations.AlterField(
            model_name='cosinnusconferencepremiumblock',
            name='to_date',
            field=models.DateField(blank=True, default=None, help_text='During this time, the conference will be using the premium BBB server.', null=True, verbose_name='End Datetime'),
        ),
        migrations.AlterField(
            model_name='cosinnusconferencepremiumcapacityinfo',
            name='from_date',
            field=models.DateField(blank=True, default=None, help_text='The time frame while the selected capacity is available.', null=True, verbose_name='Start Datetime'),
        ),
        migrations.AlterField(
            model_name='cosinnusconferencepremiumcapacityinfo',
            name='to_date',
            field=models.DateField(blank=True, default=None, help_text='The time frame while the selected capacity is available.', null=True, verbose_name='End Datetime'),
        ),
    ]
