# Generated by Django 2.1.15 on 2021-05-18 11:37

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import re


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0108_auto_20210518_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosinnusgroup',
            name='translations',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        )
    ]
