# Generated by Django 2.1.15 on 2021-07-01 10:44

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0110_auto_20210527_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosinnusportal',
            name='userprofile_default_description',
            field=models.TextField(blank=True, null=True, verbose_name='Default description'),
        ),
    ]
