# Generated by Django 2.1.15 on 2021-08-31 14:40

import cosinnus.utils.bigbluebutton
from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0112_auto_20210819_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosinnusgroup',
            name='publicly_visible',
            field=models.BooleanField(default=True, help_text='Checks if a group/project should be visible publicly', verbose_name='Publicly visible'),
        )
    ]
