# Generated by Django 2.1.15 on 2020-12-16 11:45

from django.db import migrations
from cosinnus.conf import settings


def mark_verified_email_users(apps, schema_editor):
    """ Sets the `email_verified` field to true for all users whose email does not start with
        "__unverified__", the previous marker for unverified user accounts. """
    
    profile_app_label, profile_model_name = settings.COSINNUS_USER_PROFILE_MODEL.split('.')
    UserProfile = apps.get_model(profile_app_label, profile_model_name)
    
    verified_profiles = UserProfile.objects.exclude(user__email__startswith='__unverified__')
    verified_profiles.update(email_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0112_auto_20210722_1415'),
    ]

    operations = [
        migrations.RunPython(mark_verified_email_users, migrations.RunPython.noop),
    ]
