# Generated by Django 2.1.15 on 2021-10-13 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0115_add_translations_field'),
        ('cosinnus', '0107_auto_20210519_2103'),
    ]

    operations = [
    ]
