# Generated by Django 2.1.15 on 2021-10-22 10:31

import cosinnus.utils.bigbluebutton
from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0116_merge_20211013_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosinnusgroup',
            name='is_open_for_cooperation',
            field=models.BooleanField(default=False, verbose_name='Open for cooperation'),
        ),
    ]
