# Generated by Django 2.1.15 on 2021-10-27 08:35

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0116_auto_20211020_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosinnusgroup',
            name='video_conference_type',
            field=models.PositiveIntegerField(choices=[(1, 'BBB-Meeting'), (2, 'Fairmeeting'), (0, 'No video conference')], default=0, verbose_name='Type of video conference available for a group / a project'),
        ),
    ]
