# Generated by Django 2.1.15 on 2021-11-03 14:31

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0117_auto_20211027_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosinnusconferencesettings',
            name='cam_starts_on',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No'), (1, 'Yes'), (9999, '--- UNSET (Inherit) ---')], default=9999, help_text='Whether the camera is active when entering the BBB room', verbose_name='Turn on camera on entering'),
        ),
        migrations.AddField(
            model_name='cosinnusconferencesettings',
            name='mic_starts_on',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No'), (1, 'Yes'), (9999, '--- UNSET (Inherit) ---')], default=9999, help_text='Whether the microphone is active when entering the BBB room', verbose_name='Turn on microphone on entering'),
        ),
        migrations.AlterField(
            model_name='bbbroom',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, default=None, editable=False, help_text='DEPRECATED! Maximum number in the conference at the same time. NOTE: Seems this needs to be +1 more the number that you actually want for BBB to allow!', null=True, verbose_name='maximum number of users'),
        ),
        migrations.AlterField(
            model_name='bbbroom',
            name='options',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, editable=False, help_text='DEPRECATED! options for the room, that are represented in the bigbluebutton API', null=True, verbose_name='room options'),
        ),
        migrations.AlterField(
            model_name='bbbroom',
            name='room_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'General'), (1, 'Active'), (2, 'Restricted'), (3, 'Premium')], default=0, editable=False, help_text='DEPRECATED!', verbose_name='Room Type'),
        ),
        migrations.AlterField(
            model_name='bbbroom',
            name='welcome_message',
            field=models.CharField(blank=True, editable=False, help_text='DEPRECATED! the welcome message, that is displayed to attendees', max_length=300, null=True, verbose_name='the rooms welcome message'),
        ),
    ]
