# Generated by Django 2.2 on 2021-12-09 10:53

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import jsonfield.fields
import re
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0120_auto_20211125_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='Europe/Berlin'),
        ),
    ]
