# Generated by Django 3.2 on 2022-01-13 10:16

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0120_auto_20211125_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dynamic_fields',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Extra userprofile fields for each portal, as defined in `settings.COSINNUS_USERPROFILE_EXTRA_FIELDS`', verbose_name='Dynamic extra fields'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='extra_fields',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='NO LONGER USED! Extra userprofile fields for each portal, as defined in `settings.COSINNUS_USERPROFILE_EXTRA_FIELDS`'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='settings',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='cosinnusconferenceroom',
            name='translations',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='cosinnusgroup',
            name='translations',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='translations',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='bbbroom',
            name='options',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, editable=False, help_text='DEPRECATED! options for the room, that are represented in the bigbluebutton API', null=True, verbose_name='room options'),
        ),
        migrations.AlterField(
            model_name='bbbroomvisitstatistics',
            name='data',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='cosinnusconferenceapplication',
            name='options',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='cosinnusconferenceapplication',
            name='priorities',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Priorities'),
        ),
        migrations.AlterField(
            model_name='cosinnusconferencesettings',
            name='bbb_params',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Custom parameters for API calls like join/create for all BBB rooms for this object and in its inherited objects.', verbose_name='BBB API Parameters'),
        ),
        migrations.AlterField(
            model_name='participationmanagement',
            name='application_options',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='cosinnusgroup',
            name='dynamic_fields',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Extra group fields for each portal, as defined in `settings.COSINNUS_GROUP_EXTRA_FIELDS`', verbose_name='Dynamic extra fields'),
        ),
        migrations.AlterField(
            model_name='cosinnusgroup',
            name='extra_fields',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='cosinnusgroup',
            name='sdgs',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='cosinnusgroup',
            name='settings',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='cosinnusportal',
            name='dynamic_field_choices',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='A dict storage for all choice lists for the dynamic fields of type `DYNAMIC_FIELD_TYPE_ADMIN_DEFINED_CHOICES_TEXT`', verbose_name='Dynamic choice field choices'),
        ),
        migrations.AlterField(
            model_name='cosinnusportal',
            name='saved_infos',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='cosinnususerimport',
            name='import_data',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, editable=False, help_text='Stores the uploaded CSV data', verbose_name='Import Data'),
        ),
        migrations.AlterField(
            model_name='lastvisitedobject',
            name='item_data',
            field=models.JSONField(help_text='Stores a JSON representation of the target object, as converted by a `DashboardItem`.', verbose_name='Data', encoder=django.core.serializers.json.DjangoJSONEncoder),
        )
    ]
