# Generated by Django 2.2.24 on 2022-01-20 13:11

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0121_auto_20220119_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bbbroom',
            name='max_participants',
        ),
        migrations.RemoveField(
            model_name='bbbroom',
            name='options',
        ),
        migrations.RemoveField(
            model_name='bbbroom',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='bbbroom',
            name='welcome_message',
        ),
        migrations.AddField(
            model_name='bbbroom',
            name='last_create_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, editable=False, help_text="The parameters used for the last create call. Serves as a record only, new create params are derived from the source object's options!", null=True, verbose_name='Last create-call parameters'),
        ),
    ]
