# Generated by Django 3.2 on 2022-01-31 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0121_auto_20220113_1116'),
        ('cosinnus', '0122_auto_20220120_1411'),
    ]

    operations = [
    ]
