# Generated by Django 3.2 on 2022-01-31 13:09

import cosinnus.utils.bigbluebutton
from django.conf import settings
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosinnus', '0123_merge_0121_auto_20220113_1116_0122_auto_20220120_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbbroom',
            name='last_create_params',
            field=models.JSONField(blank=True, default=dict, editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text="The parameters used for the last create call. Serves as a record only, new create params are derived from the source object's options!", null=True, verbose_name='Letzte Create-Call Parameter'),
        ),
    ]
