# Generated by Django 3.2 on 2022-03-03 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0123_merge_20220215_1409'),
        ('cosinnus', '0124_auto_20220131_1409'),
    ]

    operations = [
    ]
