# Generated by Django 3.2 on 2022-04-13 07:38

import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0125_merge_20220303_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosinnusgroup',
            name='use_invite_token',
            field=models.BooleanField(default=False, help_text='If enabled, allows the creation of invite tokens in non-admin area', verbose_name='Use invite token'),
        ),
    ]
