# Generated by Django 3.2 on 2022-04-12 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0117_auto_20211022_1231'),
        ('cosinnus', '0125_merge_20220303_1302'),
    ]

    operations = [
    ]
