# Generated by Django 2.1.15 on 2020-11-16 07:44

from django.db import migrations
from django.db.models import F

from cosinnus.conf import settings
from cosinnus.utils.migrations import attach_swappable_dependencies
from django.core.exceptions import ImproperlyConfigured


def migrate_group_extra_fields(apps, schema_editor):
    """ Carries over all values from CosinnusGroup.extra_fields to 
        CosinnusGroup.dynamic_fields unless each key already exists """
    
    try:
        app_label, model_name = settings.COSINNUS_GROUP_OBJECT_MODEL.split('.')
    except ValueError:
        raise ImproperlyConfigured("COSINNUS_USER_PROFILE_MODEL must be defined for this migration'")
    
    CosinnusGroup = apps.get_model(app_label, model_name)
    for group in CosinnusGroup.objects.all():
        if group.extra_fields:
            changed = False
            for key in group.extra_fields:
                if not key in group.dynamic_fields:
                    group.dynamic_fields[key] = group.extra_fields[key]
                    changed = True
            if changed:
                CosinnusGroup.objects.filter(pk=group.pk).update(dynamic_fields=group.dynamic_fields)
                
    
class Migration(migrations.Migration):

    dependencies = attach_swappable_dependencies([
        ('cosinnus', '0126_merge_20220412_1613'),
    ])

    operations = [
        migrations.RunPython(migrate_group_extra_fields, migrations.RunPython.noop),
    ]
