# Generated by Django 3.2 on 2022-04-20 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0126_auto_20220413_0938'),
        ('cosinnus', '0127_migrate_group_extra_fields'),
    ]

    operations = [
    ]
