# Generated by Django 3.2 on 2022-04-25 12:03

import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0127_migrate_group_extra_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosinnusgroup',
            name='extra_fields',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='extra_fields',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='NO LONGER USED! Extra userprofile fields for each portal, as defined in `settings.COSINNUS_USERPROFILE_EXTRA_FIELDS`', null=True),
        ),
    ]
