# Generated by Django 3.2 on 2022-04-20 11:52

import django.core.serializers.json
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0127_migrate_group_extra_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cosinnusgroup',
            name='extra_fields',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='extra_fields',
        ),
    ]
