# Generated by Django 3.2.16 on 2022-11-03 15:29

import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0129_auto_20220413_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosinnusgroup',
            name='enable_user_premium_choices_until',
            field=models.DateField(blank=True, help_text='Enter the date until group admins may make premium choices here (only if group/project and event BBB rooms require a premium booking)', null=True, verbose_name='Enable premium user choices (BBB) until'),
        ),
    ]
