# Generated by Django 3.2 on 2022-07-01 12:16

import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0129_auto_20220413_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosinnusconferenceapplication',
            name='may_be_contacted',
            field=models.BooleanField(default=True, help_text='If active, conference applicant may be contacted by conference admins via email', verbose_name='Applicant may be contacted'),
        ),
        migrations.AddField(
            model_name='participationmanagement',
            name='may_be_contacted_field_enabled',
            field=models.BooleanField(default=False, help_text='If active, conference applicants will be required to enable the option to be contacted by conference admins', verbose_name='Request contact option'),
        ),
    ]
