# Generated by Django 3.2 on 2022-12-07 14:38

import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0130_auto_20220701_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbbroom',
            name='guest_token',
            field=models.CharField(blank=True, editable=False, help_text='Token for guest access to this room via https://SERVER.COM/bbb/<token>', max_length=100, null=True, unique=True),
        ),
    ]
