# Generated by Django 3.2 on 2022-12-15 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0130_auto_20220920_1232'),
        ('cosinnus', '0131_auto_20221207_1538'),
    ]

    operations = [
    ]
