# Generated by Django 3.2.16 on 2022-12-15 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0130_auto_20221103_1629'),
        ('cosinnus', '0132_merge_0130_auto_20220920_1232_0131_auto_20221207_1538'),
    ]

    operations = [
    ]
