# Generated by Django 3.2.18 on 2023-08-08 15:31

import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0134_auto_20230712_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosinnusconferenceapplication',
            name='motivation_answers',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='User motivation answers'),
        ),
        migrations.AddField(
            model_name='participationmanagement',
            name='motivation_questions',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='User motivation questions'),
        ),
    ]
