# Generated by Django 3.2.18 on 2023-09-04 11:29

from django.db import migrations


def migrate_conference_application_information(apps, schema_editor):
    """
    Migrate participant information to motivation questions and answers.
    Create a single motivation_question for ParticipationManagement "information_field_initial_text" and a single
    motivation_answer from CosinnusConferenceApplication "information".
    """

    # migrate ParticipationManagement "information_field_initial_text" to "motivation_questions"
    ParticipationManagement = apps.get_model('cosinnus', 'ParticipationManagement')
    participations = ParticipationManagement.objects.exclude(information_field_initial_text__isnull=True)
    participations = participations.exclude(information_field_initial_text='')
    for participation in participations:
        participation.motivation_questions = [{'question': participation.information_field_initial_text}]
    ParticipationManagement.objects.bulk_update(participations, ['motivation_questions'])

    # migrate CosinnusConferenceApplication "information" to "motivation_answers"
    CosinnusConferenceApplication = apps.get_model('cosinnus', 'CosinnusConferenceApplication')
    applications = CosinnusConferenceApplication.objects.exclude(information=True).exclude(information='')
    for application in applications:
        participation = ParticipationManagement.objects.filter(conference_id=application.conference_id).first()
        if participation:
            application.motivation_answers = [{
                'question': participation.information_field_initial_text,
                'answer': application.information,
            }]
    CosinnusConferenceApplication.objects.bulk_update(applications, ['motivation_answers'])


def revert_migrate_conference_application_information(apps, schema_editor):
    """ Revert migrate_conference_application_information. """

    # revert ParticipationManagement "motivation_questions" to "information_field_initial_text"
    ParticipationManagement = apps.get_model('cosinnus', 'ParticipationManagement')
    participations = ParticipationManagement.objects.exclude(motivation_questions=None)
    for participation in participations:
        if participation.motivation_questions and len(participation.motivation_questions) > 0:
            question = participation.motivation_questions[0].get('question')
            if question:
                participation.information_field_initial_text = question
    ParticipationManagement.objects.bulk_update(participations, ['information_field_initial_text'])

    # revert CosinnusConferenceApplication  "motivation_answers" to "information"
    CosinnusConferenceApplication = apps.get_model('cosinnus', 'CosinnusConferenceApplication')
    applications = CosinnusConferenceApplication.objects.exclude(motivation_answers=None)
    for application in applications:
        if participation:
            if application.motivation_answers and len(application.motivation_answers) > 0:
                answer = application.motivation_answers[0].get('answer')
                application.information = answer
    CosinnusConferenceApplication.objects.bulk_update(applications, ['information'])


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0136_auto_20230824_1318'),
    ]

    operations = [
        migrations.RunPython(migrate_conference_application_information, revert_migrate_conference_application_information),
    ]
