# Generated by Django 3.2.18 on 2023-09-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0137_migrate_conference_application_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cosinnusconferenceapplication',
            name='information',
        ),
        migrations.RemoveField(
            model_name='participationmanagement',
            name='information_field_initial_text',
        ),
    ]
