# Generated by Django 3.2.18 on 2023-10-05 14:51

import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0138_auto_20230905_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('deletion_after', models.DateTimeField(verbose_name='Deletion after')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('data', models.BinaryField(verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Temporary Data',
                'verbose_name_plural': 'Temporary Data',
                'ordering': ['-created'],
            },
        ),
    ]
