# Generated by Django 3.2.18 on 2023-10-18 12:54

from django.conf import settings
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosinnus', '0140_auto_20231010_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsnewsletter',
            name='is_sending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='is_sending',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='QueuedMassMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300, verbose_name='Subject')),
                ('content', models.TextField(verbose_name='Content')),
                ('send_mail_kwargs', models.JSONField(blank=True, default=dict, null=True, verbose_name='Mail function kwargs')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('sending_in_progress', models.BooleanField(default=False, verbose_name='Sending in Progress')),
                ('recipients', models.ManyToManyField(related_name='queued_mass_mails', to=settings.AUTH_USER_MODEL, verbose_name='Recipients')),
                ('recipients_sent', models.ManyToManyField(related_name='queued_mass_mails_sent', to=settings.AUTH_USER_MODEL, verbose_name='Mails sent to Recipients')),
            ],
            options={
                'verbose_name': 'Queued Mass Mail',
                'verbose_name_plural': 'Queued Mass Mails',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='groupsnewsletter',
            name='queued_mail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cosinnus.queuedmassmail'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='queued_mail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cosinnus.queuedmassmail'),
        ),
    ]
