# Generated by Django 3.2.18 on 2023-10-04 09:36

from django.conf import settings
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosinnus', '0141_auto_20231018_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='_is_guest',
            field=models.BooleanField(default=False, editable=False, verbose_name='May be contacted'),
        ),
        migrations.CreateModel(
            name='UserGroupGuestAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.SlugField(help_text='The token string. It will be displayed as it is, but when users enter it, upper/lower-case do not matter. Can contain letters and numbers, but no spaces, and can be as long or short as you want.', unique=True, verbose_name='Token')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_group_guest_access', to=settings.COSINNUS_GROUP_OBJECT_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='guest_access_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_users', to='cosinnus.usergroupguestaccess'),
        ),
    ]
