# Generated by Django 4.2.9 on 2024-01-31 14:57

from django.conf import settings
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosinnus', '0142_auto_20231124_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosinnusportal',
            name='translations',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
