# Generated by Django 4.2.9 on 2024-02-26 15:14

from django.conf import settings
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosinnus', '0143_cosinnusportal_add_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosinnusgroup',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Subtitle used for conferences.', max_length=250, null=True, verbose_name='Subtitle'),
        ),
    ]
