# Generated by Django 4.2.9 on 2024-03-18 14:46

from django.conf import settings
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cosinnus", "0145_user_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="email_verified",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Email verified"
            ),
        ),
    ]
