# Generated by Django 4.2.9 on 2024-03-18 14:59

from django.conf import settings
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cosinnus", "0146_cosinnusprofile_email_verified_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="tos_accepted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="ToS accepted"
            ),
        ),
    ]
