# Generated by Django 4.2.14 on 2024-10-21 12:06

from django.conf import settings
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosinnus', '0149_migrate_tos_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosinnusgroupmembership',
            name='is_late_invitation',
            field=models.BooleanField(default=False, verbose_name='Is Late Invitation'),
        ),
    ]
