# Generated by Django 4.2.13 on 2024-07-09 12:24

from django.conf import settings
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosinnus', '0150_group_scheduled_for_deletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosinnusgroup',
            name='inactivity_notification_sent_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Inactivity notification sent at'),
        ),
        migrations.AddField(
            model_name='cosinnusgroup',
            name='last_activity',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Last activity'),
        ),
    ]
