# Generated by Django 4.2.13 on 2024-07-22 12:31

from django.conf import settings
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosinnus', '0151_group_activity_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='inactivity_notification_sent_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Inactivity notification sent at'),
        ),
    ]
