# Generated by Django 4.2.11 on 2025-04-30 15:00

import cosinnus.utils.bigbluebutton
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosinnus', '0151_participationmanagement_add_application_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOnlineOnDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, editable=False, verbose_name='Date')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='online_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Online on Day',
                'verbose_name_plural': 'User Online on Day',
                'ordering': ['-date'],
                'unique_together': {('date', 'user')},
            },
        ),
    ]
