# Generated by Django 4.2.11 on 2025-05-07 14:57

import cosinnus.utils.bigbluebutton
import cosinnus.utils.files
from django.conf import settings
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosinnus', '0152_add_useronlineday_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='MitwirkomatSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('is_active', models.BooleanField(default=False, help_text='Determines if the Mitwirk-O-Mat data for this group should displayed in the API.', verbose_name='Is active')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Replacement description for the group description. If empty, falls back to `group.description_long` falls back to `group.description`.', max_length=750, null=True, verbose_name='Description')),
                ('avatar', models.ImageField(blank=True, help_text='Replacement avatar for the group avatar. If empty, falls back to group.avatar.', max_length=250, null=True, upload_to=cosinnus.utils.files.get_mitwirkomat_avatar_filename, verbose_name='Avatar')),
                ('questions', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='User-set answers to Mitwirk-O-Mat questions')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mitwirkomat_settings', to=settings.COSINNUS_GROUP_OBJECT_MODEL, verbose_name='Group for Mitwirk-O-Mat Settings')),
            ],
            options={
                'verbose_name': 'Mitwirk-O-Mat Settings',
                'verbose_name_plural': 'Mitwirk-O-Mat Settings',
            },
        ),
    ]
