# Generated by Django 4.2.21 on 2025-05-15 11:58

import cosinnus.utils.bigbluebutton
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosinnus', '0154_add_userblock_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosinnusgroup',
            name='nextcloud_deck_board_id',
            field=models.PositiveIntegerField(blank=True, help_text='Internal ID of the nextcloud deck board for the group. Set after the deck is created.', null=True, unique=True, verbose_name='Nextcloud Deck Board ID'),
        ),
    ]
