# Generated by Django 4.2.11 on 2025-08-06 11:05

import cosinnus.utils.bigbluebutton
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosinnus', '0154_add_userblock_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosinnusportal',
            name='accounts_need_verification',
            field=models.BooleanField(default=False, help_text='If activated, newly registered users will not be able to post in the Forum and other autojoin until specifically approved by an admin (checkbox `account_verified` in the user profile).', verbose_name='Accounts Need Verification'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='account_verified',
            field=models.BooleanField(default=True, help_text='Whether admin approval for newly registered accounts has been given that this user may post in the Forum and other autojoin groups.', verbose_name='Account verified'),
        ),
    ]
