# Generated by Django 4.2.11 on 2025-07-23 13:51

import cosinnus.utils.bigbluebutton
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosinnus', '0154_cosinnusgroup_add_nextcloud_deck_board_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('blocked_user', models.ForeignKey(help_text='The target user for the block.', on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL, verbose_name='Target User')),
                ('user', models.ForeignKey(help_text='User who has marked a target user as blocked.', on_delete=django.db.models.deletion.CASCADE, related_name='user_blocks', to=settings.AUTH_USER_MODEL, verbose_name='Source User')),
            ],
            options={
                'verbose_name': 'User-Block',
                'verbose_name_plural': 'User-Blocks',
                'unique_together': {('user', 'blocked_user')},
            },
        ),
    ]
