# Generated by Django 4.2.21 on 2025-06-19 10:56

import cosinnus.utils.bigbluebutton
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosinnus', '0155_cosinnusconference_alter_cosinnusmanagedtag_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagobject',
            name='migrated',
            field=models.BooleanField(default=False),
        ),
    ]
