# Generated by Django 4.2.13 on 2024-07-04 08:43

from django.conf import settings
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosinnus', '0156_tagobject_add_migrated'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosinnusgroup',
            name='deletion_triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Scheduled for Deletion by'),
        ),
        migrations.AddField(
            model_name='cosinnusgroup',
            name='scheduled_for_deletion_at',
            field=models.DateTimeField(blank=True, default=None, help_text='The date this group is scheduled for deletion. Will be deleted after this date (ONLY IF the group is set to inactive!)', null=True, verbose_name='Scheduled for Deletion at'),
        ),
    ]
