# Generated by Django 4.2.11 on 2025-08-07 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0155_add_account_verified_fields_to_portal_and_profile'),
        ('cosinnus', '0156_tagobject_add_migrated'),
    ]

    operations = [
    ]
