# Generated by Django 4.2.21 on 2025-08-14 13:27

import cosinnus.models.mixins.indexes
import cosinnus.models.tagged
import cosinnus.utils.bigbluebutton
from django.conf import settings
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosinnus', '0157_merge_0155_and_0156'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncedExternalObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=55)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('last_action', models.DateTimeField(auto_now_add=True, help_text='A datetime for when a significant action last happened for this object, which users might be interested in. I.e. new comments, special edits, etc.', verbose_name='Last action date')),
                ('settings', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('object_type', models.CharField(max_length=250)),
                ('object_id', models.CharField(max_length=250)),
                ('url', models.URLField(null=True)),
                ('icon', models.CharField(max_length=250)),
                ('attached_objects', models.ManyToManyField(blank=True, to='cosinnus.attachedobject')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.COSINNUS_GROUP_OBJECT_MODEL, verbose_name='Team')),
                ('last_action_user', models.ForeignKey(help_text='The user which caused the last significant action to update the `last_action` datetime.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last action user')),
                ('media_tag', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.COSINNUS_TAG_OBJECT_MODEL)),
            ],
            options={
                'unique_together': {('object_type', 'object_id')},
            },
            bases=(cosinnus.models.tagged.LastVisitedMixin, cosinnus.models.mixins.indexes.IndexingUtilsMixin, models.Model),
        ),
    ]
