# Generated by Django 4.2.11 on 2025-09-25 12:15

import cosinnus.utils.bigbluebutton
from django.conf import settings
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosinnus', '0158_add_syncedexternalobject_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitwirkomatsettings',
            name='dynamic_fields',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Extra mitwirkomat filter fields for each portal, as defined in `settings.COSINNUS_MITWIRKOMAT_EXTRA_FIELDS`', verbose_name='Dynamic extra fields'),
        ),
        migrations.AlterField(
            model_name='mitwirkomatsettings',
            name='description',
            field=models.TextField(blank=True, help_text='Replacement description for the group description. If empty, falls back to `group.description_long` which falls back to `group.description`.', max_length=750, null=True, verbose_name='Description'),
        ),
    ]
