# Generated by Django 4.2.27 on 2025-12-09 14:47

import cosinnus.utils.bigbluebutton
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosinnus', '0159_mitwirkomatsettings_add_dynamicfields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosinnusgroup',
            name='nextcloud_calendar_url',
            field=models.URLField(blank=True, help_text='CalDAV URL of the nextcloud calendar for the group. Set after the calendar is created.', null=True, unique=True, verbose_name='Nextcloud Group Calendar CalDAV URL'),
        ),
    ]
