# Generated by Django 4.2.27 on 2026-01-21 10:41

import cosinnus.utils.bigbluebutton
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosinnus', '0160_cosinnusgroup_add_nextcloud_calendar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagobject',
            name='external_video_conference_url',
            field=models.URLField(blank=True, null=True, verbose_name='External Video Conference URL'),
        ),
        migrations.AddField(
            model_name='tagobject',
            name='location_type',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Location Type'),
        ),
    ]
