# Generated by Django 4.2.27 on 2026-02-26 10:52

import cosinnus.utils.bigbluebutton
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosinnus', '0161_tagobject_add_location_type_and_external_video_conference_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagobject',
            name='show_bbb_guest_access_outside_of_conference',
            field=models.BooleanField(default=False, verbose_name='Show BBB guest access outside of conference.'),
        ),
    ]
