# Generated by Django 4.2.27 on 2026-03-10 09:00

import cosinnus.utils.bigbluebutton
from django.conf import settings
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosinnus', '0165_tagobject_add_show_bbb_guest_access_outside_of_conference'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagobject',
            name='dynamic_fields',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Extra tagged object fields for each portal, as defined in `settings.COSINNUS_TAGGED_EXTRA_FIELDS`', verbose_name='Dynamic extra fields'),
        ),
    ]
