# Generated by Django 4.2.27 on 2026-04-27 12:20

import cosinnus.utils.bigbluebutton
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosinnus', '0166_tagobject_add_dynamic_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosinnusgroup',
            name='nextcloud_calendar_publish_url',
            field=models.URLField(blank=True, help_text='CalDAV Publish URL of the nextcloud calendar for the group. Set after the calendar is created.', null=True, unique=True, verbose_name='Nextcloud Group Calendar CalDAV Publish URL'),
        ),
    ]
