# Generated by Django 4.2.27 on 2026-05-19 12:59

import cosinnus.utils.bigbluebutton
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosinnus', '0167_cosinnusgroup_add_nextcloud_calendar_publish_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosinnusgroup',
            name='nextcloud_calendar_last_sync',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Nextcloud Group Calendar CalDAV Last Sync Timestamp'),
        ),
        migrations.AddField(
            model_name='cosinnusgroup',
            name='nextcloud_calendar_sync_token',
            field=models.CharField(blank=True, help_text='Clear to enforce a re-sync off all events.', max_length=255, null=True, verbose_name='Nextcloud Group Calendar CalDAV Sync-Token'),
        ),
    ]
