# Generated by Django 4.2.27 on 2026-06-09 08:41

import cosinnus.utils.bigbluebutton
import cosinnus.utils.files
import cosinnus.utils.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosinnus', '0168_cosinnusgroup_calendar_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosinnusgroup',
            name='nextcloud_calendar_sync_required',
            field=models.BooleanField(default=False, verbose_name='Nextcloud Group Calendar CalDAV Sync Required'),
        ),
    ]
