# Generated by Django 4.2.30 on 2026-06-03 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0164_migrate_portal_group_setting'),
        ('cosinnus', '0168_cosinnusgroup_calendar_sync'),
    ]

    operations = [
    ]
