# Generated by Django 4.2.27 on 2026-06-11 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0169_cosinnusgroup_add_nextcloud_calendar_sync_required'),
        ('cosinnus', '0169_merge_20260603_1358'),
    ]

    operations = [
    ]
