# Generated by Django 4.2.27 on 2026-06-23 09:38

import cosinnus.utils.bigbluebutton
import cosinnus.utils.files
import cosinnus.utils.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosinnus', '0169_cosinnusgroup_add_nextcloud_calendar_sync_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosinnusgroup',
            name='nextcloud_calendar_ctag',
            field=models.CharField(blank=True, help_text='Clear to enforce a re-sync off group events.', max_length=255, null=True, verbose_name='Nextcloud Group Calendar CalDAV CTag'),
        ),
    ]
