# Generated by Django 4.2.30 on 2026-05-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0170_cosinnusgroup_add_nextcloud_calendar_ctag'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalusernotificationsetting',
            name='portal_group_setting',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Never (we will not send you any emails)'),
                                                            (1, 'Immediately (an individual email per event)'),
                                                            (2, 'In a Daily Report'), (3, 'In a Weekly Report')],
                                                   default=0,
                                                   help_text='Determines if the user wants no mail, immediate mails, aggregated mails for portal-wide default groups'),
        ),
    ]
