# Generated by Django 4.2.30 on 2026-06-03 10:07
import logging

from django.db import migrations, transaction

from cosinnus.conf import settings

ALL_NOTIFICATIONS_ID = 'notifications__all'
SETTING_GROUP_INDIVIDUAL = 4

logger = logging.getLogger('cosinnus')

def forwards(apps, schema_editor):
    """Populate portal_group_setting values."""
    group_app_name, group_model_name = settings.COSINNUS_GROUP_OBJECT_MODEL.split('.')
    CosinnusGroupModel = apps.get_model(group_app_name, group_model_name)

    GlobalUserNotificationSetting = apps.get_model(
        "cosinnus",
        "GlobalUserNotificationSetting",
    )
    UserNotificationPreference = apps.get_model(
        "cosinnus_notifications",
        "UserNotificationPreference",
    )

    default_portal_group_slugs = set(
        filter(None, [
            getattr(settings, "NEWW_FORUM_GROUP_SLUG", None),
            getattr(settings, "NEWW_EVENTS_GROUP_SLUG", None),
            *getattr(settings, "NEWW_DEFAULT_USER_GROUPS", []),
        ])
    )

    if not default_portal_group_slugs:
        return

    default_group = CosinnusGroupModel.objects.filter(slug__in=default_portal_group_slugs).order_by('id').first()

    if not default_group:
        return

    portal = default_group.portal
    for user in portal.users.all().iterator():
        settings_obj, _created = GlobalUserNotificationSetting.objects.get_or_create(user=user, portal=portal)
        try:
            with transaction.atomic():
                new_portal_group_setting = settings_obj.setting

                # use the pref for the first default group as the new setting,
                # if one exists and the user has global settings on INDIVIDUAL
                if settings_obj.setting == SETTING_GROUP_INDIVIDUAL:
                    default_pref = UserNotificationPreference.objects.filter(user=user,
                                                                             notification_id=ALL_NOTIFICATIONS_ID,
                                                                             group_id=default_group.id).first()
                    if default_pref:
                        new_portal_group_setting = default_pref.setting

                # skip update if value does not need to be updated
                if new_portal_group_setting == settings_obj.portal_group_setting:
                    continue
                # update needed
                settings_obj.portal_group_setting = new_portal_group_setting
                settings_obj.save(update_fields=['portal_group_setting'])
        except Exception as e:
            logger.exception(f'Failed to migrate the new portal group setting for user {user.id}, using existing/default value. Error: {e}')


class Migration(migrations.Migration):
    # commit changes per user
    atomic = False

    dependencies = [
        ('cosinnus', '0171_add_portal_group_setting'),
        ('cosinnus_notifications', '0010_auto_20220117_1735'),
    ]

    # old values stay in the db, rollback is a NOP
    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
