# Generated by Django 4.2.27 on 2026-08-11 14:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosinnus', '0172_migrate_portal_group_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdashboardannouncement',
            name='call_to_action_active',
            field=models.BooleanField(default=False, verbose_name='Call to Action Buttons active'),
        ),
        migrations.AddField(
            model_name='userdashboardannouncement',
            name='display',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Image + 1 column of text'), (1, '2 columns of text')], default=0, verbose_name='Display'),
        ),
        migrations.AddField(
            model_name='userdashboardannouncement',
            name='text_col_1',
            field=models.TextField(blank=True, verbose_name='Text (1. column)'),
        ),
        migrations.AddField(
            model_name='userdashboardannouncement',
            name='text_col_2',
            field=models.TextField(blank=True, verbose_name='Text (2. column)'),
        ),
        migrations.CreateModel(
            name='UserDashboardCallToActionButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=250, verbose_name='Button Text')),
                ('url', models.URLField(validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='Button URL')),
                ('dashboard_announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_to_action_buttons', to='cosinnus.userdashboardannouncement', verbose_name='Dashboard Announcement')),
            ],
            options={
                'verbose_name': 'Dashboard Announcement CallToAction Button',
                'verbose_name_plural': 'Dashboard Announcement CallToAction Buttons',
            },
        ),
    ]
