# Generated by Django 4.2.27 on 2026-08-13 11:21

import cosinnus.models.mixins.images
import cosinnus.utils.bigbluebutton
import cosinnus.utils.files
import cosinnus.utils.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosinnus', '0173_userdashboard_add_display_text_cols_and_cta_buttons'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDashboardWelcomeAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, help_text='If an idea is not active, it counts as non-existent for all purposes and views on the website.', verbose_name='Is active')),
                ('title', models.CharField(help_text='Internal title field only.', max_length=250, verbose_name='Title')),
                ('display', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Image + 1 column of text'), (1, '2 columns of text')], default=0, verbose_name='Display')),
                ('text', models.TextField(blank=True, help_text='Main text of this announcement.', verbose_name='Text')),
                ('image', models.ImageField(blank=True, help_text='Shown as large banner image', max_length=250, null=True, upload_to=cosinnus.utils.files.get_user_dashboard_announcement_image_filename, verbose_name='Image')),
                ('text_col_1', models.TextField(blank=True, verbose_name='Text (1. column)')),
                ('text_col_2', models.TextField(blank=True, verbose_name='Text (2. column)')),
                ('call_to_action_active', models.BooleanField(default=False, verbose_name='Call to Action Buttons active')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('display_duration', models.SmallIntegerField(default=30, verbose_name='Display duration in days')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'abstract': False,
            },
            bases=(cosinnus.models.mixins.images.ThumbnailableImageMixin, models.Model),
        ),
        migrations.RenameModel(
            old_name='UserDashboardCallToActionButton',
            new_name='UserDashboardAnnouncementCallToActionButton',
        ),
        migrations.CreateModel(
            name='UserDashboardWelcomeAnnouncementCallToActionButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=250, verbose_name='Button Text')),
                ('url', models.URLField(validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='Button URL')),
                ('welcome_announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_to_action_buttons', to='cosinnus.userdashboardwelcomeannouncement', verbose_name='Welcome Announcement')),
            ],
            options={
                'verbose_name': 'Dashboard Announcement CallToAction Button',
                'verbose_name_plural': 'Dashboard Announcement CallToAction Buttons',
            },
        ),
    ]
