# Generated by Django 4.2.27 on 2026-09-15 08:38

import cosinnus.utils.bigbluebutton
import cosinnus.utils.files
import cosinnus.utils.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosinnus', '0174_add_userdashboard_welcome_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_avatar_generated',
            field=models.BooleanField(default=False, verbose_name='Avatar is generated'),
        ),
    ]
