# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0039_auto_20180926_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboarddoublecolumnpage',
            name='banner_left_de',
        ),
        migrations.RemoveField(
            model_name='dashboarddoublecolumnpage',
            name='banner_left_en',
        ),
        migrations.RemoveField(
            model_name='dashboarddoublecolumnpage',
            name='banner_left_fr',
        ),
        migrations.RemoveField(
            model_name='dashboarddoublecolumnpage',
            name='banner_left_pl',
        ),
        migrations.RemoveField(
            model_name='dashboarddoublecolumnpage',
            name='banner_left_ru',
        ),
        migrations.RemoveField(
            model_name='dashboarddoublecolumnpage',
            name='banner_left_uk',
        ),
        migrations.RemoveField(
            model_name='dashboarddoublecolumnpage',
            name='banner_right_de',
        ),
        migrations.RemoveField(
            model_name='dashboarddoublecolumnpage',
            name='banner_right_en',
        ),
        migrations.RemoveField(
            model_name='dashboarddoublecolumnpage',
            name='banner_right_fr',
        ),
        migrations.RemoveField(
            model_name='dashboarddoublecolumnpage',
            name='banner_right_pl',
        ),
        migrations.RemoveField(
            model_name='dashboarddoublecolumnpage',
            name='banner_right_ru',
        ),
        migrations.RemoveField(
            model_name='dashboarddoublecolumnpage',
            name='banner_right_uk',
        ),
        migrations.RemoveField(
            model_name='dashboarddoublecolumnpage',
            name='content1_de',
        ),
        migrations.RemoveField(
            model_name='dashboarddoublecolumnpage',
            name='content1_en',
        ),
        migrations.RemoveField(
            model_name='dashboarddoublecolumnpage',
            name='content1_fr',
        ),
        migrations.RemoveField(
            model_name='dashboarddoublecolumnpage',
            name='content1_pl',
        ),
        migrations.RemoveField(
            model_name='dashboarddoublecolumnpage',
            name='content1_ru',
        ),
        migrations.RemoveField(
            model_name='dashboarddoublecolumnpage',
            name='content1_uk',
        ),
        migrations.RemoveField(
            model_name='dashboarddoublecolumnpage',
            name='content2_de',
        ),
        migrations.RemoveField(
            model_name='dashboarddoublecolumnpage',
            name='content2_en',
        ),
        migrations.RemoveField(
            model_name='dashboarddoublecolumnpage',
            name='content2_fr',
        ),
        migrations.RemoveField(
            model_name='dashboarddoublecolumnpage',
            name='content2_pl',
        ),
        migrations.RemoveField(
            model_name='dashboarddoublecolumnpage',
            name='content2_ru',
        ),
        migrations.RemoveField(
            model_name='dashboarddoublecolumnpage',
            name='content2_uk',
        ),
        migrations.RemoveField(
            model_name='dashboarddoublecolumnpage',
            name='footer_left_de',
        ),
        migrations.RemoveField(
            model_name='dashboarddoublecolumnpage',
            name='footer_left_en',
        ),
        migrations.RemoveField(
            model_name='dashboarddoublecolumnpage',
            name='footer_left_fr',
        ),
        migrations.RemoveField(
            model_name='dashboarddoublecolumnpage',
            name='footer_left_pl',
        ),
        migrations.RemoveField(
            model_name='dashboarddoublecolumnpage',
            name='footer_left_ru',
        ),
        migrations.RemoveField(
            model_name='dashboarddoublecolumnpage',
            name='footer_left_uk',
        ),
        migrations.RemoveField(
            model_name='dashboarddoublecolumnpage',
            name='footer_right_de',
        ),
        migrations.RemoveField(
            model_name='dashboarddoublecolumnpage',
            name='footer_right_en',
        ),
        migrations.RemoveField(
            model_name='dashboarddoublecolumnpage',
            name='footer_right_fr',
        ),
        migrations.RemoveField(
            model_name='dashboarddoublecolumnpage',
            name='footer_right_pl',
        ),
        migrations.RemoveField(
            model_name='dashboarddoublecolumnpage',
            name='footer_right_ru',
        ),
        migrations.RemoveField(
            model_name='dashboarddoublecolumnpage',
            name='footer_right_uk',
        ),
        migrations.RemoveField(
            model_name='dashboarddoublecolumnpage',
            name='header_de',
        ),
        migrations.RemoveField(
            model_name='dashboarddoublecolumnpage',
            name='header_en',
        ),
        migrations.RemoveField(
            model_name='dashboarddoublecolumnpage',
            name='header_fr',
        ),
        migrations.RemoveField(
            model_name='dashboarddoublecolumnpage',
            name='header_pl',
        ),
        migrations.RemoveField(
            model_name='dashboarddoublecolumnpage',
            name='header_ru',
        ),
        migrations.RemoveField(
            model_name='dashboarddoublecolumnpage',
            name='header_uk',
        ),
        migrations.RemoveField(
            model_name='dashboarddoublecolumnpage',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='dashboarddoublecolumnpage',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='dashboarddoublecolumnpage',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='dashboarddoublecolumnpage',
            name='title_pl',
        ),
        migrations.RemoveField(
            model_name='dashboarddoublecolumnpage',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='dashboarddoublecolumnpage',
            name='title_uk',
        ),
        migrations.RemoveField(
            model_name='dashboardsinglecolumnpage',
            name='banner_left_de',
        ),
        migrations.RemoveField(
            model_name='dashboardsinglecolumnpage',
            name='banner_left_en',
        ),
        migrations.RemoveField(
            model_name='dashboardsinglecolumnpage',
            name='banner_left_fr',
        ),
        migrations.RemoveField(
            model_name='dashboardsinglecolumnpage',
            name='banner_left_pl',
        ),
        migrations.RemoveField(
            model_name='dashboardsinglecolumnpage',
            name='banner_left_ru',
        ),
        migrations.RemoveField(
            model_name='dashboardsinglecolumnpage',
            name='banner_left_uk',
        ),
        migrations.RemoveField(
            model_name='dashboardsinglecolumnpage',
            name='banner_right_de',
        ),
        migrations.RemoveField(
            model_name='dashboardsinglecolumnpage',
            name='banner_right_en',
        ),
        migrations.RemoveField(
            model_name='dashboardsinglecolumnpage',
            name='banner_right_fr',
        ),
        migrations.RemoveField(
            model_name='dashboardsinglecolumnpage',
            name='banner_right_pl',
        ),
        migrations.RemoveField(
            model_name='dashboardsinglecolumnpage',
            name='banner_right_ru',
        ),
        migrations.RemoveField(
            model_name='dashboardsinglecolumnpage',
            name='banner_right_uk',
        ),
        migrations.RemoveField(
            model_name='dashboardsinglecolumnpage',
            name='content1_de',
        ),
        migrations.RemoveField(
            model_name='dashboardsinglecolumnpage',
            name='content1_en',
        ),
        migrations.RemoveField(
            model_name='dashboardsinglecolumnpage',
            name='content1_fr',
        ),
        migrations.RemoveField(
            model_name='dashboardsinglecolumnpage',
            name='content1_pl',
        ),
        migrations.RemoveField(
            model_name='dashboardsinglecolumnpage',
            name='content1_ru',
        ),
        migrations.RemoveField(
            model_name='dashboardsinglecolumnpage',
            name='content1_uk',
        ),
        migrations.RemoveField(
            model_name='dashboardsinglecolumnpage',
            name='footer_left_de',
        ),
        migrations.RemoveField(
            model_name='dashboardsinglecolumnpage',
            name='footer_left_en',
        ),
        migrations.RemoveField(
            model_name='dashboardsinglecolumnpage',
            name='footer_left_fr',
        ),
        migrations.RemoveField(
            model_name='dashboardsinglecolumnpage',
            name='footer_left_pl',
        ),
        migrations.RemoveField(
            model_name='dashboardsinglecolumnpage',
            name='footer_left_ru',
        ),
        migrations.RemoveField(
            model_name='dashboardsinglecolumnpage',
            name='footer_left_uk',
        ),
        migrations.RemoveField(
            model_name='dashboardsinglecolumnpage',
            name='footer_right_de',
        ),
        migrations.RemoveField(
            model_name='dashboardsinglecolumnpage',
            name='footer_right_en',
        ),
        migrations.RemoveField(
            model_name='dashboardsinglecolumnpage',
            name='footer_right_fr',
        ),
        migrations.RemoveField(
            model_name='dashboardsinglecolumnpage',
            name='footer_right_pl',
        ),
        migrations.RemoveField(
            model_name='dashboardsinglecolumnpage',
            name='footer_right_ru',
        ),
        migrations.RemoveField(
            model_name='dashboardsinglecolumnpage',
            name='footer_right_uk',
        ),
        migrations.RemoveField(
            model_name='dashboardsinglecolumnpage',
            name='header_de',
        ),
        migrations.RemoveField(
            model_name='dashboardsinglecolumnpage',
            name='header_en',
        ),
        migrations.RemoveField(
            model_name='dashboardsinglecolumnpage',
            name='header_fr',
        ),
        migrations.RemoveField(
            model_name='dashboardsinglecolumnpage',
            name='header_pl',
        ),
        migrations.RemoveField(
            model_name='dashboardsinglecolumnpage',
            name='header_ru',
        ),
        migrations.RemoveField(
            model_name='dashboardsinglecolumnpage',
            name='header_uk',
        ),
        migrations.RemoveField(
            model_name='dashboardsinglecolumnpage',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='dashboardsinglecolumnpage',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='dashboardsinglecolumnpage',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='dashboardsinglecolumnpage',
            name='title_pl',
        ),
        migrations.RemoveField(
            model_name='dashboardsinglecolumnpage',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='dashboardsinglecolumnpage',
            name='title_uk',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='banner_left_de',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='banner_left_en',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='banner_left_fr',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='banner_left_pl',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='banner_left_ru',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='banner_left_uk',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='banner_right_de',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='banner_right_en',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='banner_right_fr',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='banner_right_pl',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='banner_right_ru',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='banner_right_uk',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='content1_de',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='content1_en',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='content1_fr',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='content1_pl',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='content1_ru',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='content1_uk',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='content2_de',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='content2_en',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='content2_fr',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='content2_pl',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='content2_ru',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='content2_uk',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='content3_de',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='content3_en',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='content3_fr',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='content3_pl',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='content3_ru',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='content3_uk',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='footer_left_de',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='footer_left_en',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='footer_left_fr',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='footer_left_pl',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='footer_left_ru',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='footer_left_uk',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='footer_right_de',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='footer_right_en',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='footer_right_fr',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='footer_right_pl',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='footer_right_ru',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='footer_right_uk',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='header_de',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='header_en',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='header_fr',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='header_pl',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='header_ru',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='header_uk',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='title_pl',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='dashboardtriplecolumnpage',
            name='title_uk',
        ),
        migrations.RemoveField(
            model_name='portalrootpage',
            name='footer_de',
        ),
        migrations.RemoveField(
            model_name='portalrootpage',
            name='footer_en',
        ),
        migrations.RemoveField(
            model_name='portalrootpage',
            name='footer_fr',
        ),
        migrations.RemoveField(
            model_name='portalrootpage',
            name='footer_pl',
        ),
        migrations.RemoveField(
            model_name='portalrootpage',
            name='footer_ru',
        ),
        migrations.RemoveField(
            model_name='portalrootpage',
            name='footer_uk',
        ),
        migrations.RemoveField(
            model_name='portalrootpage',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='portalrootpage',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='portalrootpage',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='portalrootpage',
            name='title_pl',
        ),
        migrations.RemoveField(
            model_name='portalrootpage',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='portalrootpage',
            name='title_uk',
        ),
        migrations.RemoveField(
            model_name='simpleonepage',
            name='content_de',
        ),
        migrations.RemoveField(
            model_name='simpleonepage',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='simpleonepage',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='simpleonepage',
            name='content_pl',
        ),
        migrations.RemoveField(
            model_name='simpleonepage',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='simpleonepage',
            name='content_uk',
        ),
        migrations.RemoveField(
            model_name='simpleonepage',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='simpleonepage',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='simpleonepage',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='simpleonepage',
            name='title_pl',
        ),
        migrations.RemoveField(
            model_name='simpleonepage',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='simpleonepage',
            name='title_uk',
        ),
        migrations.RemoveField(
            model_name='simpletwopage',
            name='content_de',
        ),
        migrations.RemoveField(
            model_name='simpletwopage',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='simpletwopage',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='simpletwopage',
            name='content_pl',
        ),
        migrations.RemoveField(
            model_name='simpletwopage',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='simpletwopage',
            name='content_uk',
        ),
        migrations.RemoveField(
            model_name='simpletwopage',
            name='leftnav_de',
        ),
        migrations.RemoveField(
            model_name='simpletwopage',
            name='leftnav_en',
        ),
        migrations.RemoveField(
            model_name='simpletwopage',
            name='leftnav_fr',
        ),
        migrations.RemoveField(
            model_name='simpletwopage',
            name='leftnav_pl',
        ),
        migrations.RemoveField(
            model_name='simpletwopage',
            name='leftnav_ru',
        ),
        migrations.RemoveField(
            model_name='simpletwopage',
            name='leftnav_uk',
        ),
        migrations.RemoveField(
            model_name='simpletwopage',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='simpletwopage',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='simpletwopage',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='simpletwopage',
            name='title_pl',
        ),
        migrations.RemoveField(
            model_name='simpletwopage',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='simpletwopage',
            name='title_uk',
        ),
        migrations.RemoveField(
            model_name='streamdashboarddoublecolumnpage',
            name='banner_left_de',
        ),
        migrations.RemoveField(
            model_name='streamdashboarddoublecolumnpage',
            name='banner_left_en',
        ),
        migrations.RemoveField(
            model_name='streamdashboarddoublecolumnpage',
            name='banner_left_fr',
        ),
        migrations.RemoveField(
            model_name='streamdashboarddoublecolumnpage',
            name='banner_left_pl',
        ),
        migrations.RemoveField(
            model_name='streamdashboarddoublecolumnpage',
            name='banner_left_ru',
        ),
        migrations.RemoveField(
            model_name='streamdashboarddoublecolumnpage',
            name='banner_left_uk',
        ),
        migrations.RemoveField(
            model_name='streamdashboarddoublecolumnpage',
            name='banner_right_de',
        ),
        migrations.RemoveField(
            model_name='streamdashboarddoublecolumnpage',
            name='banner_right_en',
        ),
        migrations.RemoveField(
            model_name='streamdashboarddoublecolumnpage',
            name='banner_right_fr',
        ),
        migrations.RemoveField(
            model_name='streamdashboarddoublecolumnpage',
            name='banner_right_pl',
        ),
        migrations.RemoveField(
            model_name='streamdashboarddoublecolumnpage',
            name='banner_right_ru',
        ),
        migrations.RemoveField(
            model_name='streamdashboarddoublecolumnpage',
            name='banner_right_uk',
        ),
        migrations.RemoveField(
            model_name='streamdashboarddoublecolumnpage',
            name='content1_de',
        ),
        migrations.RemoveField(
            model_name='streamdashboarddoublecolumnpage',
            name='content1_en',
        ),
        migrations.RemoveField(
            model_name='streamdashboarddoublecolumnpage',
            name='content1_fr',
        ),
        migrations.RemoveField(
            model_name='streamdashboarddoublecolumnpage',
            name='content1_pl',
        ),
        migrations.RemoveField(
            model_name='streamdashboarddoublecolumnpage',
            name='content1_ru',
        ),
        migrations.RemoveField(
            model_name='streamdashboarddoublecolumnpage',
            name='content1_uk',
        ),
        migrations.RemoveField(
            model_name='streamdashboarddoublecolumnpage',
            name='content2_de',
        ),
        migrations.RemoveField(
            model_name='streamdashboarddoublecolumnpage',
            name='content2_en',
        ),
        migrations.RemoveField(
            model_name='streamdashboarddoublecolumnpage',
            name='content2_fr',
        ),
        migrations.RemoveField(
            model_name='streamdashboarddoublecolumnpage',
            name='content2_pl',
        ),
        migrations.RemoveField(
            model_name='streamdashboarddoublecolumnpage',
            name='content2_ru',
        ),
        migrations.RemoveField(
            model_name='streamdashboarddoublecolumnpage',
            name='content2_uk',
        ),
        migrations.RemoveField(
            model_name='streamdashboarddoublecolumnpage',
            name='footer_left_de',
        ),
        migrations.RemoveField(
            model_name='streamdashboarddoublecolumnpage',
            name='footer_left_en',
        ),
        migrations.RemoveField(
            model_name='streamdashboarddoublecolumnpage',
            name='footer_left_fr',
        ),
        migrations.RemoveField(
            model_name='streamdashboarddoublecolumnpage',
            name='footer_left_pl',
        ),
        migrations.RemoveField(
            model_name='streamdashboarddoublecolumnpage',
            name='footer_left_ru',
        ),
        migrations.RemoveField(
            model_name='streamdashboarddoublecolumnpage',
            name='footer_left_uk',
        ),
        migrations.RemoveField(
            model_name='streamdashboarddoublecolumnpage',
            name='footer_right_de',
        ),
        migrations.RemoveField(
            model_name='streamdashboarddoublecolumnpage',
            name='footer_right_en',
        ),
        migrations.RemoveField(
            model_name='streamdashboarddoublecolumnpage',
            name='footer_right_fr',
        ),
        migrations.RemoveField(
            model_name='streamdashboarddoublecolumnpage',
            name='footer_right_pl',
        ),
        migrations.RemoveField(
            model_name='streamdashboarddoublecolumnpage',
            name='footer_right_ru',
        ),
        migrations.RemoveField(
            model_name='streamdashboarddoublecolumnpage',
            name='footer_right_uk',
        ),
        migrations.RemoveField(
            model_name='streamdashboarddoublecolumnpage',
            name='header_de',
        ),
        migrations.RemoveField(
            model_name='streamdashboarddoublecolumnpage',
            name='header_en',
        ),
        migrations.RemoveField(
            model_name='streamdashboarddoublecolumnpage',
            name='header_fr',
        ),
        migrations.RemoveField(
            model_name='streamdashboarddoublecolumnpage',
            name='header_pl',
        ),
        migrations.RemoveField(
            model_name='streamdashboarddoublecolumnpage',
            name='header_ru',
        ),
        migrations.RemoveField(
            model_name='streamdashboarddoublecolumnpage',
            name='header_uk',
        ),
        migrations.RemoveField(
            model_name='streamdashboarddoublecolumnpage',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='streamdashboarddoublecolumnpage',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='streamdashboarddoublecolumnpage',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='streamdashboarddoublecolumnpage',
            name='title_pl',
        ),
        migrations.RemoveField(
            model_name='streamdashboarddoublecolumnpage',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='streamdashboarddoublecolumnpage',
            name='title_uk',
        ),
        migrations.RemoveField(
            model_name='streamdashboardsinglecolumnpage',
            name='banner_left_de',
        ),
        migrations.RemoveField(
            model_name='streamdashboardsinglecolumnpage',
            name='banner_left_en',
        ),
        migrations.RemoveField(
            model_name='streamdashboardsinglecolumnpage',
            name='banner_left_fr',
        ),
        migrations.RemoveField(
            model_name='streamdashboardsinglecolumnpage',
            name='banner_left_pl',
        ),
        migrations.RemoveField(
            model_name='streamdashboardsinglecolumnpage',
            name='banner_left_ru',
        ),
        migrations.RemoveField(
            model_name='streamdashboardsinglecolumnpage',
            name='banner_left_uk',
        ),
        migrations.RemoveField(
            model_name='streamdashboardsinglecolumnpage',
            name='banner_right_de',
        ),
        migrations.RemoveField(
            model_name='streamdashboardsinglecolumnpage',
            name='banner_right_en',
        ),
        migrations.RemoveField(
            model_name='streamdashboardsinglecolumnpage',
            name='banner_right_fr',
        ),
        migrations.RemoveField(
            model_name='streamdashboardsinglecolumnpage',
            name='banner_right_pl',
        ),
        migrations.RemoveField(
            model_name='streamdashboardsinglecolumnpage',
            name='banner_right_ru',
        ),
        migrations.RemoveField(
            model_name='streamdashboardsinglecolumnpage',
            name='banner_right_uk',
        ),
        migrations.RemoveField(
            model_name='streamdashboardsinglecolumnpage',
            name='content1_de',
        ),
        migrations.RemoveField(
            model_name='streamdashboardsinglecolumnpage',
            name='content1_en',
        ),
        migrations.RemoveField(
            model_name='streamdashboardsinglecolumnpage',
            name='content1_fr',
        ),
        migrations.RemoveField(
            model_name='streamdashboardsinglecolumnpage',
            name='content1_pl',
        ),
        migrations.RemoveField(
            model_name='streamdashboardsinglecolumnpage',
            name='content1_ru',
        ),
        migrations.RemoveField(
            model_name='streamdashboardsinglecolumnpage',
            name='content1_uk',
        ),
        migrations.RemoveField(
            model_name='streamdashboardsinglecolumnpage',
            name='footer_left_de',
        ),
        migrations.RemoveField(
            model_name='streamdashboardsinglecolumnpage',
            name='footer_left_en',
        ),
        migrations.RemoveField(
            model_name='streamdashboardsinglecolumnpage',
            name='footer_left_fr',
        ),
        migrations.RemoveField(
            model_name='streamdashboardsinglecolumnpage',
            name='footer_left_pl',
        ),
        migrations.RemoveField(
            model_name='streamdashboardsinglecolumnpage',
            name='footer_left_ru',
        ),
        migrations.RemoveField(
            model_name='streamdashboardsinglecolumnpage',
            name='footer_left_uk',
        ),
        migrations.RemoveField(
            model_name='streamdashboardsinglecolumnpage',
            name='footer_right_de',
        ),
        migrations.RemoveField(
            model_name='streamdashboardsinglecolumnpage',
            name='footer_right_en',
        ),
        migrations.RemoveField(
            model_name='streamdashboardsinglecolumnpage',
            name='footer_right_fr',
        ),
        migrations.RemoveField(
            model_name='streamdashboardsinglecolumnpage',
            name='footer_right_pl',
        ),
        migrations.RemoveField(
            model_name='streamdashboardsinglecolumnpage',
            name='footer_right_ru',
        ),
        migrations.RemoveField(
            model_name='streamdashboardsinglecolumnpage',
            name='footer_right_uk',
        ),
        migrations.RemoveField(
            model_name='streamdashboardsinglecolumnpage',
            name='header_de',
        ),
        migrations.RemoveField(
            model_name='streamdashboardsinglecolumnpage',
            name='header_en',
        ),
        migrations.RemoveField(
            model_name='streamdashboardsinglecolumnpage',
            name='header_fr',
        ),
        migrations.RemoveField(
            model_name='streamdashboardsinglecolumnpage',
            name='header_pl',
        ),
        migrations.RemoveField(
            model_name='streamdashboardsinglecolumnpage',
            name='header_ru',
        ),
        migrations.RemoveField(
            model_name='streamdashboardsinglecolumnpage',
            name='header_uk',
        ),
        migrations.RemoveField(
            model_name='streamdashboardsinglecolumnpage',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='streamdashboardsinglecolumnpage',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='streamdashboardsinglecolumnpage',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='streamdashboardsinglecolumnpage',
            name='title_pl',
        ),
        migrations.RemoveField(
            model_name='streamdashboardsinglecolumnpage',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='streamdashboardsinglecolumnpage',
            name='title_uk',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='banner_left_de',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='banner_left_en',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='banner_left_fr',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='banner_left_pl',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='banner_left_ru',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='banner_left_uk',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='banner_right_de',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='banner_right_en',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='banner_right_fr',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='banner_right_pl',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='banner_right_ru',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='banner_right_uk',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='content1_de',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='content1_en',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='content1_fr',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='content1_pl',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='content1_ru',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='content1_uk',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='content2_de',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='content2_en',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='content2_fr',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='content2_pl',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='content2_ru',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='content2_uk',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='content3_de',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='content3_en',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='content3_fr',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='content3_pl',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='content3_ru',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='content3_uk',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='footer_left_de',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='footer_left_en',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='footer_left_fr',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='footer_left_pl',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='footer_left_ru',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='footer_left_uk',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='footer_right_de',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='footer_right_en',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='footer_right_fr',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='footer_right_pl',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='footer_right_ru',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='footer_right_uk',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='header_de',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='header_en',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='header_fr',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='header_pl',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='header_ru',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='header_uk',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='title_pl',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='streamdashboardtriplecolumnpage',
            name='title_uk',
        ),
        migrations.RemoveField(
            model_name='streamsimpleonepage',
            name='content_de',
        ),
        migrations.RemoveField(
            model_name='streamsimpleonepage',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='streamsimpleonepage',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='streamsimpleonepage',
            name='content_pl',
        ),
        migrations.RemoveField(
            model_name='streamsimpleonepage',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='streamsimpleonepage',
            name='content_uk',
        ),
        migrations.RemoveField(
            model_name='streamsimpleonepage',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='streamsimpleonepage',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='streamsimpleonepage',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='streamsimpleonepage',
            name='title_pl',
        ),
        migrations.RemoveField(
            model_name='streamsimpleonepage',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='streamsimpleonepage',
            name='title_uk',
        ),
        migrations.RemoveField(
            model_name='streamsimpletwopage',
            name='content_de',
        ),
        migrations.RemoveField(
            model_name='streamsimpletwopage',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='streamsimpletwopage',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='streamsimpletwopage',
            name='content_pl',
        ),
        migrations.RemoveField(
            model_name='streamsimpletwopage',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='streamsimpletwopage',
            name='content_uk',
        ),
        migrations.RemoveField(
            model_name='streamsimpletwopage',
            name='leftnav_de',
        ),
        migrations.RemoveField(
            model_name='streamsimpletwopage',
            name='leftnav_en',
        ),
        migrations.RemoveField(
            model_name='streamsimpletwopage',
            name='leftnav_fr',
        ),
        migrations.RemoveField(
            model_name='streamsimpletwopage',
            name='leftnav_pl',
        ),
        migrations.RemoveField(
            model_name='streamsimpletwopage',
            name='leftnav_ru',
        ),
        migrations.RemoveField(
            model_name='streamsimpletwopage',
            name='leftnav_uk',
        ),
        migrations.RemoveField(
            model_name='streamsimpletwopage',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='streamsimpletwopage',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='streamsimpletwopage',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='streamsimpletwopage',
            name='title_pl',
        ),
        migrations.RemoveField(
            model_name='streamsimpletwopage',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='streamsimpletwopage',
            name='title_uk',
        ),
        migrations.RemoveField(
            model_name='streamstartpage',
            name='bottom_content_de',
        ),
        migrations.RemoveField(
            model_name='streamstartpage',
            name='bottom_content_en',
        ),
        migrations.RemoveField(
            model_name='streamstartpage',
            name='bottom_content_fr',
        ),
        migrations.RemoveField(
            model_name='streamstartpage',
            name='bottom_content_pl',
        ),
        migrations.RemoveField(
            model_name='streamstartpage',
            name='bottom_content_ru',
        ),
        migrations.RemoveField(
            model_name='streamstartpage',
            name='bottom_content_uk',
        ),
        migrations.RemoveField(
            model_name='streamstartpage',
            name='header_content_de',
        ),
        migrations.RemoveField(
            model_name='streamstartpage',
            name='header_content_en',
        ),
        migrations.RemoveField(
            model_name='streamstartpage',
            name='header_content_fr',
        ),
        migrations.RemoveField(
            model_name='streamstartpage',
            name='header_content_pl',
        ),
        migrations.RemoveField(
            model_name='streamstartpage',
            name='header_content_ru',
        ),
        migrations.RemoveField(
            model_name='streamstartpage',
            name='header_content_uk',
        ),
        migrations.RemoveField(
            model_name='streamstartpage',
            name='header_image_de',
        ),
        migrations.RemoveField(
            model_name='streamstartpage',
            name='header_image_en',
        ),
        migrations.RemoveField(
            model_name='streamstartpage',
            name='header_image_fr',
        ),
        migrations.RemoveField(
            model_name='streamstartpage',
            name='header_image_pl',
        ),
        migrations.RemoveField(
            model_name='streamstartpage',
            name='header_image_ru',
        ),
        migrations.RemoveField(
            model_name='streamstartpage',
            name='header_image_uk',
        ),
        migrations.RemoveField(
            model_name='streamstartpage',
            name='header_text_de',
        ),
        migrations.RemoveField(
            model_name='streamstartpage',
            name='header_text_en',
        ),
        migrations.RemoveField(
            model_name='streamstartpage',
            name='header_text_fr',
        ),
        migrations.RemoveField(
            model_name='streamstartpage',
            name='header_text_pl',
        ),
        migrations.RemoveField(
            model_name='streamstartpage',
            name='header_text_ru',
        ),
        migrations.RemoveField(
            model_name='streamstartpage',
            name='header_text_uk',
        ),
        migrations.RemoveField(
            model_name='streamstartpage',
            name='header_title_de',
        ),
        migrations.RemoveField(
            model_name='streamstartpage',
            name='header_title_en',
        ),
        migrations.RemoveField(
            model_name='streamstartpage',
            name='header_title_fr',
        ),
        migrations.RemoveField(
            model_name='streamstartpage',
            name='header_title_pl',
        ),
        migrations.RemoveField(
            model_name='streamstartpage',
            name='header_title_ru',
        ),
        migrations.RemoveField(
            model_name='streamstartpage',
            name='header_title_uk',
        ),
        migrations.RemoveField(
            model_name='streamstartpage',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='streamstartpage',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='streamstartpage',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='streamstartpage',
            name='title_pl',
        ),
        migrations.RemoveField(
            model_name='streamstartpage',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='streamstartpage',
            name='title_uk',
        ),
    ]
