# Generated by Django 2.1.10 on 2020-01-22 12:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0051_auto_20191017_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosinnusgroup',
            name='nextcloud_group_id',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True, validators=[django.core.validators.MaxLengthValidator(250)], verbose_name='Nextcloud Group ID'),
        ),
    ]
