# Generated by Django 2.1.15 on 2020-05-15 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0055_auto_20200416_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosinnusgroup',
            name='nextcloud_groupfolder_id',
            field=models.PositiveIntegerField(blank=True, help_text='The boolean internal nextcloud id for the groupfolder. Only set once a groupfolder is created.', null=True, unique=True, verbose_name='Nextcloud Groupfolder ID'),
        ),
        migrations.AddField(
            model_name='cosinnusgroup',
            name='nextcloud_groupfolder_name',
            field=models.CharField(blank=True, help_text='The literal groupfolder name. This is initially the same as the group id, but can differ later. Set before the groupfolder is created.', max_length=250, null=True, unique=True, validators=[django.core.validators.MaxLengthValidator(250)], verbose_name='Nextcloud Groupfolder Name'),
        ),
    ]
