# Generated by Django 2.1.15 on 2020-09-01 11:39

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0057_add_workshop_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosinnusgroup',
            name='sdgs',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        )
    ]
