# Generated by Django 2.1.15 on 2020-09-30 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0057_merge_20200610_1758'),
        ('cosinnus', '0057_add_workshop_flags'),
    ]

    operations = [
    ]
