# Generated by Django 2.1.15 on 2020-10-05 08:15

import cosinnus.models.mixins.indexes
import cosinnus.utils.files
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import osm_field.fields
import osm_field.validators
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosinnus', '0058_merge_20200930_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosinnusgroup',
            name='extra_fields',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
        migrations.AddField(
            model_name='tagobject',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Publicly available via other platforms'),
        ),
    ]
