# Generated by Django 2.1.15 on 2020-10-12 10:50

import cosinnus.utils.files
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosinnus', '0069_merge_20201006_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='CosinnusManagedTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('slug', models.SlugField(help_text='Be extremely careful when changing this slug manually! There can be many side-effects (redirects breaking e.g.)!', verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Short Description')),
                ('image', models.ImageField(blank=True, max_length=250, null=True, upload_to=cosinnus.utils.files.get_managed_tag_image_filename, verbose_name='Image')),
                ('color', models.CharField(blank=True, help_text='Optional color code (css hex value, with or without "#")', max_length=10, null=True, validators=[django.core.validators.MaxLengthValidator(7)], verbose_name='Color')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('paired_group', models.ForeignKey(blank=True, help_text='A paired group will automatically be joined by all users assigned to this.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paired_managed_tag', to=settings.COSINNUS_GROUP_OBJECT_MODEL, verbose_name='Paired Group')),
                ('portal', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='managed_tags', to='cosinnus.CosinnusPortal', verbose_name='Portal')),
            ],
            options={
                'verbose_name': 'Managed Tag',
                'verbose_name_plural': 'Managed Tag',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CosinnusManagedTagAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('assigners', models.ManyToManyField(blank=True, help_text='A list of people who suggested making this assignment. Can be empty, and can beignored once `approved` is True.', related_name='managed_tag_assignments', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('managed_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='cosinnus.CosinnusManagedTag')),
            ],
            options={
                'verbose_name': 'Managed Tag Assignment',
                'verbose_name_plural': 'Managed Tag Assignments',
            },
        ),
        migrations.AlterUniqueTogether(
            name='cosinnusmanagedtagassignment',
            unique_together={('managed_tag', 'content_type', 'object_id')},
        ),
        migrations.AlterUniqueTogether(
            name='cosinnusmanagedtag',
            unique_together={('slug', 'portal')},
        ),
    ]
