# Generated by Django 2.1.15 on 2020-10-14 10:14

import cosinnus.models.mixins.indexes
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import re


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0070_add_managed_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cosinnusmanagedtag',
            options={'ordering': ('name',), 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='cosinnusmanagedtagassignment',
            options={'verbose_name': 'Client Assignment', 'verbose_name_plural': 'Client Assignments'},
        ),
        migrations.AddField(
            model_name='cosinnusmanagedtag',
            name='search_synonyms',
            field=models.TextField(blank=True, help_text='Comma-seperated list of phrases for which auto-complete matches, even partial, will return this object.', null=True, verbose_name='Search Synonyms'),
        ),
        migrations.AddField(
            model_name='cosinnusmanagedtag',
            name='url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='cosinnusmanagedtag',
            name='paired_group',
            field=models.ForeignKey(blank=True, help_text='A paired group will automatically be joined by all users assigned to this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paired_managed_tag', to=settings.COSINNUS_GROUP_OBJECT_MODEL, verbose_name='Paired Group'),
        ),
    ]
