# Generated by Django 2.1.15 on 2020-11-15 18:53

import cosinnus.models.mixins.indexes
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import re


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0074_auto_20201109_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='recipients_source',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='managed_tags',
            field=models.ManyToManyField(to='cosinnus.CosinnusManagedTag'),
        )
    ]
