# Generated by Django 2.1.15 on 2021-01-07 10:01

import cosinnus.models.mixins.indexes
from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosinnus', '0082_auto_20210106_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='CosinnusConferenceApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Invalid'), (2, 'Submitted'), (3, 'Waitlist'), (4, 'Accepted'), (5, 'Declined')], default=2)),
                ('options', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True)),
                ('priorities', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cosinnusconferenceapplication',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_applications', to=settings.COSINNUS_GROUP_OBJECT_MODEL, verbose_name='Confernence Application'),
        ),
        migrations.AddField(
            model_name='cosinnusconferenceapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_applications', to=settings.AUTH_USER_MODEL),
        )
    ]
