# Generated by Django 2.1.15 on 2021-09-14 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0113_mark_verified_email_users'),
        ('cosinnus', '0113_auto_20210831_1640'),
    ]

    operations = [
    ]
