# Generated by Django 2.2.24 on 2022-01-19 13:17

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0120_auto_20211125_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosinnusconferencesettings',
            name='bbb_server_choice_recording_api',
            field=models.PositiveSmallIntegerField(choices=[(0, '(None)'), (9999, '--- UNSET (Inherit) ---')], default=9999, help_text='The chosen BBB-Server/Cluster setting for connections to the recording API server. WARNING: changing this will cause new meeting connections to use the new server, even for ongoing meetings on the old server, essentially splitting a running meeting in two!', verbose_name='BBB Recording API server'),
        ),
    ]
