# Generated by Django 2.2.24 on 2022-02-15 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0121_auto_20211215_1135'),
        ('cosinnus', '0122_auto_20220120_1411'),
    ]

    operations = [
    ]
