# -*- coding: utf-8 -*-
from __future__ import unicode_literals

COSINNUS_DATETIMEPICKER_DATETIME_FORMAT = 'YYYY-MM-DD HH:mm'
COSINNUS_DATETIMEPICKER_DATE_FORMAT = 'YYYY-MM-DD'
COSINNUS_DATETIMEPICKER_TIME_FORMAT = 'HH:mm'
COSINNUS_DJANGO_DATE_FORMAT = 'n.j.Y'
COSINNUS_DJANGO_DATE_SHORT_FORMAT = 'n.j.'
COSINNUS_DJANGO_DATE_SHORT_CLEAR_FORMAT = 'M j'
COSINNUS_DJANGO_TIME_FORMAT = 'h:i A'
COSINNUS_DJANGO_DATETIME_FORMAT = 'n.j.Y h:i A'
