# Generated by Django 2.1.10 on 2019-12-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus_file', '0010_auto_20191017_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileentry',
            name='is_url',
            field=models.BooleanField(default=False, help_text='Marks that this file only consists of an URL link. The `file` field may be used to download a preview image.', verbose_name='Is URL Link'),
        ),
        migrations.AddField(
            model_name='fileentry',
            name='url',
            field=models.URLField(blank=True, help_text='For files with `is_url` set to True, this is the URL link. For actual file uploads, this is blank.', max_length=250, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='fileentry',
            name='last_action',
            field=models.DateTimeField(auto_now_add=True, help_text='A datetime for when a significant action last happened for this object, which users might be interested in. I.e. new comments, special edits, etc.', verbose_name='Last action date'),
        ),
    ]
