# Generated by Django 3.2 on 2022-06-15 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus_exchange', '0002_exchangeevent_exchangeorganization'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeConference',
            fields=[
                ('exchangebasegroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cosinnus_exchange.exchangebasegroup')),
            ],
            options={
                'managed': False,
            },
            bases=('cosinnus_exchange.exchangebasegroup',),
        ),
    ]
