BBBB BBBBBBBBBBBBB
BBB BBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBB XXXXXXBB BBBBBBBBBBBBBBBBBB BB BBBBBBBXXXXXXBBBBBBBBBBBBBBXX
        XX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX
        FFFFFFFFF
    XXXXXX
BBBBBB