from .test import *  # noqa

# enabled Payments
COSINNUS_PAYMENTS_ENABLED = True
COSINNUS_PAYMENTS_ENABLED_ADMIN_ONLY = False
PAYMENTS_USE_HOOK_INSTEAD_OF_SEND_MAIL = True
PAYMENTS_TEST_PHASE = True
PAYMENTS_ACCEPTED_PAYMENT_METHODS = [
    'dd',
]
PAYMENTS_PAYMENT_RECIPIENT_NAME = 'Die WECHANGE Genossenschaft'
PAYMENTS_SEPA_CREDITOR_ID = 'DE72ZZZ00002206684'
PAYMENTS_BETTERPAYMENT_API_DOMAIN = 'https://testapi.continentalpay.com'
