# DISCLAIMER: THIS FILE HAS BEEN GENERATED BY AI

from pathlib import Path

from django.apps import apps
from django.core.management.base import BaseCommand
from django.template import engines

from cosinnus.conf import settings


def is_relative_to(path, parent):
    try:
        Path(path).resolve().relative_to(Path(parent).resolve())
        return True
    except ValueError:
        return False


class Command(BaseCommand):
    help = 'Show templates in BASE_DIR/apps that override original templates.'

    def handle(self, *args, **options):
        base = Path(settings.BASE_PATH).resolve()
        apps_dir = base / 'apps'

        engine = engines['django'].engine

        search_roots = [
            *(Path(p).resolve() for p in engine.dirs),
            *(Path(app.path).resolve() / 'templates' for app in apps.get_app_configs()),
        ]

        found = False

        count = 0
        for template_root in sorted(apps_dir.glob('*/templates')):
            for override in sorted(template_root.rglob('*')):
                if not override.is_file():
                    continue

                name = override.relative_to(template_root).as_posix()
                override = override.resolve()

                matches = [(root / name).resolve() for root in search_roots if (root / name).exists()]

                if override not in matches:
                    continue

                originals = [
                    path for path in matches[matches.index(override) + 1 :] if not is_relative_to(path, apps_dir)
                ]

                if not originals:
                    continue

                found = True
                count += 1
                self.stdout.write(f'\n{name}')
                self.stdout.write(f'  override: {override}')

                for original in originals:
                    self.stdout.write(f'  original: {original}')
        if found:
            self.stdout.write(f'\n{count} overrides found.')
        if not found:
            self.stdout.write('No overrides found.')
