# -*- coding: utf-8 -*-
from __future__ import unicode_literals

COSINNUS_DATETIMEPICKER_DATETIME_FORMAT = 'DD.MM.YYYY HH:mm'
COSINNUS_DATETIMEPICKER_DATE_FORMAT = 'DD.MM.YYYY'
COSINNUS_DATETIMEPICKER_TIME_FORMAT = 'HH:mm'
