# Generated by Django 2.1.5 on 2019-02-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(verbose_name='Is active')),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10, verbose_name='Level')),
                ('text', models.TextField(help_text='Default text. Markdown for styling is enabled!', verbose_name='Text')),
                ('text_de', models.TextField(blank=True, help_text='Markdown for styling is enabled!', null=True, verbose_name='Text (DE only)')),
                ('text_en', models.TextField(blank=True, help_text='Markdown for styling is enabled!', null=True, verbose_name='Text (EN only)')),
                ('text_ru', models.TextField(blank=True, help_text='Markdown for styling is enabled!', null=True, verbose_name='Text (RU only)')),
                ('text_uk', models.TextField(blank=True, help_text='Markdown for styling is enabled!', null=True, verbose_name='Text (UK only)')),
                ('text_pl', models.TextField(blank=True, help_text='Markdown for styling is enabled!', null=True, verbose_name='Text (PL only)')),
                ('text_fr', models.TextField(blank=True, help_text='Markdown for styling is enabled!', null=True, verbose_name='Text (FR only)')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
            },
        ),
    ]
