import datetime
import random
import time

from django.contrib.auth import get_user_model

from cosinnus.models.group import MEMBERSHIP_ADMIN, CosinnusGroupMembership
from cosinnus.models.group_extra import CosinnusSociety
from cosinnus.models.tagged import BaseTagObject
from cosinnus.utils.threading import cosinnus_worker_thread_threading_disabled
from cosinnus_event.calendar.nextcloud_caldav import NextcloudCaldavConnection
from cosinnus_event.models import Event


class CalendarTestDataGenerator:
    """Utils to generate test groups with events for calendar load testing.
    NOTE: Not finished testing, might still have concurrency problems.
    """

    TEST_NAME_PREFIX = 'AutoGeneratedTest'
    TEST_USER_NAME = f'{TEST_NAME_PREFIX}User'

    def create_calendar_test_user(self):
        test_user = get_user_model().objects.create(
            email='auto_generated_user@example.com', first_name=self.TEST_USER_NAME, is_active=True
        )
        test_user.username = test_user.id
        test_user.save(update_fields=['username'])
        test_user.cosinnus_profile.email_verified = True
        test_user.cosinnus_profile.save()
        print(f'Test User "{self.TEST_USER_NAME}" created.')
        return test_user

    def get_calendar_test_users(self):
        return get_user_model().objects.filter(first_name__startswith=self.TEST_NAME_PREFIX)

    def create_calendar_test_group(self, test_user):
        test_group_name = f'{self.TEST_NAME_PREFIX}Group{str(random.randint(1000, 9999))}'
        test_group = CosinnusSociety.objects.create(name=test_group_name)
        time.sleep(5)
        CosinnusGroupMembership.objects.create(user=test_user, group=test_group, status=MEMBERSHIP_ADMIN)
        print(f'Test Group "{test_group_name}" created.')
        return test_group

    def get_calendar_test_groups(self):
        return CosinnusSociety.objects.filter(name__startswith=self.TEST_NAME_PREFIX)

    def create_calendar_public_test_event(self, test_user, test_group):
        today = datetime.date.today()
        test_event_name = f'{self.TEST_NAME_PREFIX}PublicEvent'
        test_event = Event.objects.create(
            title=test_event_name,
            from_date=datetime.datetime(today.year, today.month, today.day, 12),
            to_date=datetime.datetime(today.year, today.month, today.day, 13),
            creator=test_user,
            group=test_group,
            state=Event.STATE_SCHEDULED,
        )
        test_event.media_tag.visibility = BaseTagObject.VISIBILITY_ALL
        test_event.media_tag.save()
        print(f'Public Test Event created in group "{test_group.name}".')

    def create_calendar_internal_test_event(self, test_user, test_group):
        today = datetime.date.today()
        test_event_name = f'{self.TEST_NAME_PREFIX}InternalEvent'
        test_group.refresh_from_db()
        caldav = NextcloudCaldavConnection()
        calendar = caldav.caldav_client.calendar(url=test_group.nextcloud_calendar_url)
        calendar.add_event(
            dtstart=datetime.datetime(today.year, today.month, today.day, 13),
            dtend=datetime.datetime(today.year, today.month, today.day, 14),
            summary=test_event_name,
        )
        print(f'Internal Test Event created in group "{test_group.name}".')

    def create_calendar_test_data(self, group_count=1):
        with cosinnus_worker_thread_threading_disabled():
            test_user = get_user_model().objects.filter(first_name=self.TEST_USER_NAME).first()
            if not test_user:
                test_user = self.create_calendar_test_user()
                # wait for NC user creation
                time.sleep(5)
            for count in range(group_count):
                test_group = self.create_calendar_test_group(test_user)
                # wait for calendar to be created
                while True:
                    test_group.refresh_from_db()
                    if test_group.nextcloud_calendar_url:
                        break
                self.create_calendar_public_test_event(test_user, test_group)
                self.create_calendar_internal_test_event(test_user, test_group)
