# Generated by Django 2.1.15 on 2020-04-20 12:40

from django.db import migrations


def disable_deck_apps(apps, schema_editor):
    """ Deactivates the cosinnus_deck app in all groups."""
    
    CosinnusGroup = apps.get_model('cosinnus', 'CosinnusGroup')
    # Note: exclude groups that have already a deck on the dev server.
    groups = CosinnusGroup.objects.filter(nextcloud_deck_board_id=None)
    for group in groups:
        if group.deactivated_apps:
            group.deactivated_apps = ','.join(list(set(group.deactivated_apps.split(',') + ['cosinnus_deck'])))
        else:
            group.deactivated_apps = 'cosinnus_deck'
    CosinnusGroup.objects.bulk_update(groups, fields=['deactivated_apps'], batch_size=1000)


def revert_disable_deck_apps(apps, schema_editor):
    """Reverts deactivation of the cosinnus_deck app in all groups."""

    CosinnusGroup = apps.get_model('cosinnus', 'CosinnusGroup')
    groups = CosinnusGroup.objects.filter(nextcloud_deck_board_id=None)
    for group in groups:
        group.deactivated_apps = ','.join(list(set(group.deactivated_apps.split(',')) - {'cosinnus_deck'}))
    CosinnusGroup.objects.bulk_update(groups, fields=['deactivated_apps'], batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus_deck', '0001_initial'),
        ('cosinnus', '0156_tagobject_add_migrated'),
    ]

    operations = [
        migrations.RunPython(disable_deck_apps, revert_disable_deck_apps),
    ]
