# Generated by Django 2.1.5 on 2021-09-21 11:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus_note', '0010_auto_20191017_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='translations',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        )
    ]
