# -*- coding: utf-8 -*-
from __future__ import unicode_literals

COSINNUS_DATETIMEPICKER_DATETIME_FORMAT = 'YYYY-MM-DD HH:mm'
COSINNUS_DATETIMEPICKER_DATE_FORMAT = 'YYYY-MM-DD'
COSINNUS_DATETIMEPICKER_TIME_FORMAT = 'HH:mm'
