from copy import deepcopy
from unittest.mock import patch
from uuid import uuid4

from django.conf import settings
from django.test import SimpleTestCase, override_settings, tag
from haystack.backends.elasticsearch7_backend import Elasticsearch7SearchBackend

from cosinnus.backends import RobustElasticSearchBackend


class RobustElasticSearchBackendTest(SimpleTestCase):
    """Test how COSINNUS_HAYSTACK_ASCII_FOLDING_ENABLED configures the search analyzers."""

    def get_analyzers(self):
        """Return the analyzer settings generated by the custom backend."""
        # The parent initializer only sets up the Elasticsearch client and is not relevant for these unit tests.
        with patch.object(Elasticsearch7SearchBackend, '__init__', return_value=None):
            backend = RobustElasticSearchBackend()
        return backend.DEFAULT_SETTINGS['settings']['analysis']['analyzer']

    @override_settings(COSINNUS_HAYSTACK_ASCII_FOLDING_ENABLED=True)
    def test_ascii_folding_enabled(self):
        """Enable accent normalization in all analyzers when COSINNUS_HAYSTACK_ASCII_FOLDING_ENABLED is true."""
        analyzers = self.get_analyzers()

        self.assertEqual(analyzers['ngram_analyzer']['filter'], ['haystack_ngram', 'lowercase', 'asciifolding'])
        self.assertEqual(analyzers['edgengram_analyzer']['filter'], ['haystack_edgengram', 'lowercase', 'asciifolding'])
        self.assertEqual(analyzers['standard_search_analyzer']['filter'], ['lowercase', 'asciifolding'])

    @override_settings(COSINNUS_HAYSTACK_ASCII_FOLDING_ENABLED=False)
    def test_ascii_folding_disabled(self):
        """Disable accent normalization while retaining lowercase filtering when the setting is false."""
        analyzers = self.get_analyzers()

        self.assertEqual(analyzers['ngram_analyzer']['filter'], ['haystack_ngram', 'lowercase'])
        self.assertEqual(analyzers['edgengram_analyzer']['filter'], ['haystack_edgengram', 'lowercase'])
        self.assertEqual(analyzers['standard_search_analyzer']['filter'], ['lowercase'])

    @patch.object(
        Elasticsearch7SearchBackend,
        'build_schema',
        return_value=('text', {'text': {'analyzer': 'ngram_analyzer'}}),
    )
    def test_ngram_fields_use_standard_search_analyzer(self, _build_schema):
        """Assign ngram fields the search analyzer controlled by COSINNUS_HAYSTACK_ASCII_FOLDING_ENABLED."""
        # Bypass initialization because this test only extends the schema returned by Haystack.
        backend = RobustElasticSearchBackend.__new__(RobustElasticSearchBackend)

        _content_field_name, mapping = backend.build_schema({})

        self.assertEqual(mapping['text']['search_analyzer'], 'standard_search_analyzer')


@tag('elasticsearch')
@override_settings(COSINNUS_HAYSTACK_ASCII_FOLDING_ENABLED=True)
class RobustElasticSearchBackendIntegrationTest(SimpleTestCase):
    """Verify enabled COSINNUS_HAYSTACK_ASCII_FOLDING_ENABLED behavior against Elasticsearch."""

    def test_search_matches_text_without_diacritics(self):
        """Find text without query diacritics when COSINNUS_HAYSTACK_ASCII_FOLDING_ENABLED is true."""
        # A unique index keeps parallel test runs isolated from each other and from configured application indexes.
        index_name = f'cosinnus-test-{uuid4().hex}'
        connection_options = settings.HAYSTACK_CONNECTIONS['default'].copy()
        connection_options.update(INDEX_NAME=index_name, SILENTLY_FAIL=False)
        backend = RobustElasticSearchBackend('default', **connection_options)

        if not backend.conn.ping():
            self.skipTest('Elasticsearch is not available.')

        # Use the backend's real analyzer settings with the smallest mapping needed for this integration test.
        index_settings = deepcopy(backend.DEFAULT_SETTINGS)
        index_settings['mappings'] = {
            'properties': {
                'text': {
                    'type': 'text',
                    'analyzer': 'ngram_analyzer',
                    'search_analyzer': 'standard_search_analyzer',
                }
            }
        }

        try:
            backend.conn.indices.create(index=index_name, body=index_settings)
            # Wait for the refresh so the following search can immediately see the document.
            backend.conn.index(index=index_name, id='1', body={'text': 'Fördérung'}, refresh='wait_for')

            result = backend.conn.search(index=index_name, body={'query': {'match': {'text': 'Forderung'}}})

            self.assertEqual(result['hits']['total']['value'], 1)
        finally:
            # Always remove the temporary index, including after a failed assertion.
            backend.conn.indices.delete(index=index_name, ignore=404)
