# Generated by Django 2.1.15 on 2020-09-16 12:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosinnus', '0060_bbbroom_portal'),
        ('cosinnus_event', '0010_auto_20190714_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cosinnus_event.Event')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Lobby Check-in'), (1, 'Stage Event'), (2, 'Workshop'), (3, 'Discussion'), (4, 'Coffee Table')], default=2, verbose_name='Conference Event Type')),
                ('is_break', models.BooleanField(default=False, help_text='If an event is a break, no rooms will be created for it, and it will be displayed differently', verbose_name='Is a Break')),
                ('max_participants', models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(512)], verbose_name='Maximum Event Participants')),
                ('presenters', models.ManyToManyField(blank=True, help_text='A list of users that will be displayed as presenters and become BBB moderators in attached rooms', related_name='_conferenceevent_presenters_+', to=settings.AUTH_USER_MODEL, verbose_name='Presenters')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cosinnus.CosinnusConferenceRoom', verbose_name='Room')),
            ],
            options={
                'verbose_name': 'Conference Event',
                'verbose_name_plural': 'Conference Events',
                'ordering': ['from_date', 'to_date'],
                'abstract': False,
            },
            bases=('cosinnus_event.event',),
        ),
    ]
