# Generated by Django 2.1.15 on 2020-09-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus_event', '0011_auto_20200916_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conferenceevent',
            options={'ordering': ['from_date', 'to_date', 'title'], 'verbose_name': 'Conference Event', 'verbose_name_plural': 'Conference Events'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['from_date', 'to_date', 'title'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterField(
            model_name='conferenceevent',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Lobby Check-in Event'), (1, 'Stage Stream'), (2, 'Workshop'), (3, 'Discussion'), (4, 'Coffee Table')], default=2, verbose_name='Conference Event Type'),
        ),
        migrations.AlterField(
            model_name='event',
            name='last_action',
            field=models.DateTimeField(auto_now_add=True, help_text='A datetime for when a significant action last happened for this object, which users might be interested in. I.e. new comments, special edits, etc.', verbose_name='Last action date'),
        ),
    ]
