# Generated by Django 2.1.15 on 2020-11-18 00:00

import cosinnus.utils.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus_event', '0013_conferenceevent_raw_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenceevent',
            name='presentation_file',
            field=models.FileField(blank=True, help_text='The presentation file (e.g. PDF) will be pre-uploaded to the BBB room.', null=True, upload_to=cosinnus.utils.files.get_presentation_filename, verbose_name='Presentation file'),
        ),
        migrations.AlterField(
            model_name='conferenceevent',
            name='raw_html',
            field=models.TextField(blank=True, default='', help_text='Raw HTML embed code to use instead of URL', null=True, verbose_name='Embed code (HTML)'),
        ),
    ]
