# Generated by Django 2.1.15 on 2021-05-22 15:53

from django.db import migrations


def set_non_cafe_max_participants(apps, schema_editor):
    """ Sets all non-cafe conference events' max_participants to 500
        because the count used to only apply to coffee table types,
        but now can potentially affect all table types, and the previous
        dormant value was too low to go into effect unexpectedly on legacy events. """
    
    ConferenceEvent = apps.get_model('cosinnus_event', 'conferenceevent')
    non_cafe_events = ConferenceEvent.objects.exclude(type=4)
    non_cafe_events.update(max_participants=500)
    

class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus_event', '0016_auto_20210519_1231'),
    ]

    operations = [
        migrations.RunPython(set_non_cafe_max_participants, migrations.RunPython.noop),
    ]
