# Generated by Django 2.1.15 on 2021-05-25 12:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus_event', '0017_set_non_cafe_max_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='translations',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
