# Generated by Django 2.2 on 2022-02-18 14:32

import cosinnus_event.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus_event', '0023_set_is_confidential_to_is_description_visible_on_microsite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferenceevent',
            name='is_confidential',
        ),
    ]
