# Generated by Django 2.1.5 on 2019-05-13 13:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosinnus', '0045_cosinnusportal_tos_date'),
        ('cosinnus_notifications', '0007_auto_20181130_1852'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usermultinotificationpreference',
            unique_together={('user', 'multi_notification_id', 'portal')},
        ),
    ]
