# Generated by Django 3.2 on 2022-01-17 16:35

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus_notifications', '0009_notificationalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationalert',
            name='bundle_list',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Only filled if type==TYPE_BUNDLE_ALERT, None else.Contains a list of objects for referenced content objects [{"object_id", "title", "url", "icon_or_image_url"}, ...]', null=True),
        ),
        migrations.AlterField(
            model_name='notificationalert',
            name='multi_user_list',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Only filled if type==TYPE_MULTI_USER_ALERT, None else.Contains a list of objects for referenced users [{"user_id", "title" (username), "url", "icon_or_image_url"}, ...]', null=True),
        ),
    ]
