# Generated by Django 4.2.27 on 2026-05-21 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosinnus_notifications', '0010_auto_20220117_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationalert',
            options={'ordering': ('-last_event_at',)},
        ),
        migrations.AlterField(
            model_name='notificationevent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User who caused this notification event'),
        ),
        migrations.AlterField(
            model_name='notificationalert',
            name='action_user',
            field=models.ForeignKey(
                help_text='For multi-user alerts, this points to the last user who changed anything about this alert.',
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL,
                verbose_name='Last user who caused this notification event'),
        ),
    ]
