# Generated by Django 2.1.15 on 2021-03-27 16:28

import cosinnus.models.mixins.indexes
import cosinnus.models.tagged
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosinnus', '0102_remove_use_conference_application'),
        migrations.swappable_dependency(settings.COSINNUS_GROUP_OBJECT_MODEL),
        migrations.swappable_dependency(settings.COSINNUS_TAG_OBJECT_MODEL),
        ('cosinnus_cloud', '0002_deactivate_group_clouds'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedCloudFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=55)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('last_action', models.DateTimeField(auto_now_add=True, help_text='A datetime for when a significant action last happened for this object, which users might be interested in. I.e. new comments, special edits, etc.', verbose_name='Last action date')),
                ('settings', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('nextcloud_file_id', models.IntegerField(unique=True, verbose_name='Nextcloud File ID')),
                ('path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Path')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('attached_objects', models.ManyToManyField(blank=True, to='cosinnus.AttachedObject')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cosinnus_cloud_linkedcloudfile_set', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cosinnus_cloud_linkedcloudfile_set', to=settings.COSINNUS_GROUP_OBJECT_MODEL, verbose_name='Team')),
                ('last_action_user', models.ForeignKey(help_text='The user which caused the last significant action to update the `last_action` datetime.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last action user')),
                ('media_tag', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.COSINNUS_TAG_OBJECT_MODEL)),
            ],
            options={
                'verbose_name': 'Linked Cloud File',
                'verbose_name_plural': 'Linked Cloud Files',
                'abstract': False,
            },
            bases=(cosinnus.models.tagged.LastVisitedMixin, cosinnus.models.mixins.indexes.IndexingUtilsMixin, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='linkedcloudfile',
            unique_together={('group', 'slug')},
        ),
    ]
